Repository stoplightio/spectral, pull requests merged in 2019-08, with the labels that each got.

#432 feat: register rules against specific formats
  src/__tests__/linter.test.ts
  src/cli/commands/__tests__/lint.test.ts
  src/cli/commands/lint.ts
  src/meta/rule.schema.json
  src/meta/ruleset.schema.json
  src/resolved.ts
  src/rulesets/__tests__/__fixtures__/my-open-api-ruleset.json
  src/rulesets/__tests__/lookups.spec.ts
  src/rulesets/__tests__/merger.test.ts
  src/rulesets/__tests__/reader.jest.test.ts
  src/rulesets/__tests__/validation.test.ts
  src/rulesets/lookups.ts
  src/rulesets/merger.ts
  src/rulesets/oas/index.json
  src/rulesets/oas2/index.json
  src/rulesets/oas3/index.json
  src/rulesets/reader.ts
  src/runner.ts
  src/spectral.ts
  src/types/rule.ts
  src/types/ruleset.ts
  src/types/spectral.ts
Labels: enhancement

#431 feat: implement loadRuleset method
  __karma__/fetch.js
  docs/guides/javascript.md
  karma.conf.ts
  package.json
  src/__tests__/__fixtures__/custom-oas-ruleset.json
  src/__tests__/spectral.jest.test.ts
  src/__tests__/spectral.karma.test.ts
  src/rulesets/__tests__/finder.jest.test.ts
  src/rulesets/__tests__/finder.karma.test.ts
  src/rulesets/__tests__/reader.jest.test.ts
  src/rulesets/finder.ts
  src/spectral.ts
  yarn.lock
Labels: enhancement

#449 fix: improve no matched formats case handling
  src/__tests__/linter.test.ts
  src/resolved.ts
  src/runner.ts
  src/spectral.ts
Labels: bug

#454 feat: support refs in rulesets
  package.json
  src/__tests__/linter.test.ts
  src/__tests__/spectral.jest.test.ts
  src/__tests__/spectral.karma.test.ts
  src/functions/__tests__/schema.test.ts
  src/functions/schema.ts
  src/rulesets/__tests__/reader.jest.test.ts
  src/rulesets/__tests__/reader.karma.test.ts
  src/rulesets/oas2/__tests__/oas2-schema.ts
  src/rulesets/oas2/index.json
  src/rulesets/oas3/index.json
  src/rulesets/reader.ts
Labels: enhancement

#458 fix: unescape json path properly
  src/__tests__/__fixtures__/studio-default-fixture-oas3.json
  src/__tests__/linter.test.ts
  src/linter.ts
  src/rulesets/oas2/__tests__/oas2-schema.ts
Labels: bug

#459 fix: do not generate non-existing paths
  karma.conf.ts
  package.json
  setupKarma.ts
  src/__tests__/linter.test.ts
  src/__tests__/spectral.jest.test.ts
  src/__tests__/spectral.karma.test.ts
  src/__tests__/spectral.test.ts
  src/cli/commands/__tests__/lint.test.ts
  src/functions/__tests__/schema-path.test.ts
  src/functions/schema-path.ts
  src/linter.ts
  src/rulesets/__tests__/reader.jest.test.ts
  src/rulesets/__tests__/reader.karma.test.ts
  src/rulesets/__tests__/reader.test.ts
  src/rulesets/oas/__tests__/contact-properties.ts
  src/rulesets/oas/__tests__/info-contact.ts
  src/rulesets/oas/__tests__/info-description.ts
  src/rulesets/oas/__tests__/info-license.ts
  src/rulesets/oas/__tests__/license-url.ts
  src/rulesets/oas/__tests__/openapi-tags.ts
  src/rulesets/oas/__tests__/operation-default-response.ts
  src/rulesets/oas/__tests__/operation-description.ts
  src/rulesets/oas/__tests__/operation-operationId.ts
  src/rulesets/oas/__tests__/operation-tags.ts
  src/rulesets/oas/__tests__/parameter-description.ts
  src/rulesets/oas/__tests__/tag-description.ts
  src/rulesets/oas2/__tests__/api-host.ts
  src/rulesets/oas2/__tests__/api-schemes.ts
  src/rulesets/oas2/__tests__/model-description.ts
  src/rulesets/oas2/__tests__/valid-example.ts
  src/rulesets/oas2/index.json
  src/rulesets/oas3/__tests__/api-servers.ts
  src/rulesets/oas3/__tests__/model-description.ts
  src/rulesets/oas3/__tests__/valid-example.ts
  src/rulesets/oas3/index.json
  tsconfig.json
  tsconfig.karma.json
Labels: bug

#433 feat: expose resolved document
  src/__tests__/linter.test.ts
  src/resolved.ts
  src/spectral.ts
  src/types/spectral.ts
Labels: enhancement

#477 fix(cli): resolve relative document paths
  package.json
  src/__tests__/__fixtures__/gh-474/common.yaml
  src/__tests__/__fixtures__/gh-474/spec-2.yaml
  src/__tests__/__fixtures__/gh-474/spec.yaml
  src/__tests__/spectral.test.ts
  src/cli/commands/__tests__/lint.test.ts
  src/cli/commands/lint.ts
  src/spectral.ts
  yarn.lock
Labels: bug

#461 feat: handle circular rulesets
  src/__tests__/__fixtures__/custom-directory-function-ruleset.json
  src/__tests__/__fixtures__/custom-functions-oas-ruleset.json
  src/__tests__/__fixtures__/custom-oas-ruleset.json
  src/__tests__/linter.test.ts
  src/__tests__/spectral.jest.test.ts
  src/__tests__/spectral.karma.test.ts
  src/__tests__/spectral.test.ts
  src/cli/commands/__tests__/__fixtures__/ruleset-valid.yaml
  src/cli/commands/__tests__/__fixtures__/spectral.yml
  src/cli/commands/__tests__/lint.test.ts
  src/cli/commands/lint.ts
  src/rulesets/__tests__/__fixtures__/bar-extends-foo-ruleset.json
  src/rulesets/__tests__/__fixtures__/custom-functions-directory-ruleset.json
  src/rulesets/__tests__/__fixtures__/extends-oas2-with-override-ruleset.json
  src/rulesets/__tests__/__fixtures__/foo-extends-bar-ruleset.json
  src/rulesets/__tests__/__fixtures__/self-extending-ruleset.json
  src/rulesets/__tests__/__fixtures__/valid-flat-ruleset.json
  src/rulesets/__tests__/reader.jest.test.ts
  src/rulesets/mergers/rules.ts
  src/rulesets/oas/__tests__/valid-example.ts
  src/rulesets/oas/functions/__tests__/oasOpSecurityDefined.test.ts
  src/rulesets/oas/index.json
  src/rulesets/oas2/index.json
  src/rulesets/oas3/__tests__/valid-example.ts
  src/rulesets/oas3/index.json
  src/rulesets/reader.ts
Labels: enhancement

#460 feat: transferable rulesets
  package.json
  scripts/compile-rulesets.js
  src/cli/commands/lint.ts
  src/fs/reader.ts
  src/rulesets/__tests__/reader.jest.test.ts
  src/rulesets/__tests__/validation.test.ts
  src/rulesets/evaluators.ts
  src/rulesets/loader.ts
  src/rulesets/mergers/__tests__/functions.jest.test.ts
  src/rulesets/mergers/functions.ts
  src/rulesets/reader.ts
  src/rulesets/validation.ts
  src/spectral.ts
  src/types/ruleset.ts
  yarn.lock
Labels: tech-debt

#473 feat: $ref cannot have siblings
  docs/getting-started/rulesets.md
  rollup.config.js
  src/__tests__/functions.test.ts
  src/__tests__/linter.test.ts
  src/linter.ts
  src/meta/rule.schema.json
  src/resolved.ts
  src/rulesets/oas/functions/__tests__/refSiblings.test.ts
  src/rulesets/oas/functions/refSiblings.ts
  src/rulesets/oas/index.json
  src/rulesets/oas/index.ts
  src/runner.ts
  src/spectral.ts
  src/types/rule.ts
  src/types/spectral.ts
  yarn.lock
Labels: enhancement

#499 feat: YAML 1.2
  docs/guides/javascript.md
  package.json
  src/__tests__/__fixtures__/implicit-strings.oas3.yaml
  src/__tests__/parsing.jest.test.ts
  yarn.lock
Labels: enhancement

#496 fix: generate proper paths and ranges for documents with $refs
  package.json
  src/__tests__/__fixtures__/document-with-external-refs.oas2.json
  src/__tests__/__fixtures__/models/todo-full.v1.json
  src/__tests__/spectral.jest.test.ts
  src/resolved.ts
  yarn.lock
Labels: bug

#501 fix(encoding): use utf8 instead of utf-8
  src/rulesets/__tests__/reader.jest.test.ts
  src/rulesets/reader.ts
Labels: bug

#503 fix: supress unknown format AJV error
  src/functions/__tests__/schema.test.ts
  src/functions/schema.ts
Labels: bug

#502 fix(rulesets): false severity should always be respected
  src/rulesets/__tests__/__fixtures__/simple-disable-ruleset.yaml
  src/rulesets/__tests__/reader.jest.test.ts
  src/rulesets/mergers/rules.ts
Labels: bug

#472 Handle example keyword validation
  docs/reference/functions.md
  src/__tests__/__fixtures__/todos.invalid.oas2.json
  src/__tests__/linter.test.ts
  src/rulesets/oas/__tests__/valid-example.ts
  src/rulesets/oas/index.json
  src/rulesets/oas2/__tests__/valid-example-in-definitions.ts
  src/rulesets/oas2/__tests__/valid-example-in-parameters.ts
  src/rulesets/oas2/index.json
  src/rulesets/oas3/__tests__/templates/_oas-example.ts
  src/rulesets/oas3/__tests__/templates/_schema-example.ts
  src/rulesets/oas3/__tests__/valid-example-in-schemas.ts
  src/rulesets/oas3/__tests__/valid-oas-example-in-content.ts
  src/rulesets/oas3/__tests__/valid-oas-example-in-headers.ts
  src/rulesets/oas3/__tests__/valid-oas-example-in-parameters.ts
  src/rulesets/oas3/__tests__/valid-schema-example-in-content.ts
  src/rulesets/oas3/__tests__/valid-schema-example-in-headers.ts
  src/rulesets/oas3/__tests__/valid-schema-example-in-parameters.ts
  src/rulesets/oas3/index.json
Labels: bug
