Repository stoplightio/spectral, pull requests merged in 2019-12, with the labels that each got.

#824 fix: print falsy value in error messages
  src/rulesets/__tests__/message.spec.ts
  src/rulesets/message.ts
Labels: bug

#825 Add two formatters: text, teamcity.
  .nvmrc
  src/cli/services/output.ts
  src/formatters/__tests__/teamcity.test.ts
  src/formatters/__tests__/text.test.ts
  src/formatters/index.ts
  src/formatters/teamcity.ts
  src/formatters/text.ts
  src/types/config.ts
Labels: enhancement

#835 fix: preserve order of properties
  package.json
  src/cli/services/linter/linter.ts
  src/functions/__tests__/alphabetical.test.ts
  src/index.ts
  src/parsers/index.ts
  src/parsers/json.ts
  src/parsers/yaml.ts
  src/spectral.ts
  test-harness/scenarios/alphabetical-responses-order.oas3.scenario
  yarn.lock
Labels: bug

#685 fix: improve error source detection
  package.json
  rollup.config.js
  src/__tests__/__fixtures__/gh-658/URIError.yaml
  src/__tests__/__fixtures__/gh-658/lib.yaml
  src/__tests__/spectral.jest.test.ts
  src/__tests__/spectral.test.ts
  src/cli/services/__tests__/linter.test.ts
  src/error-messages.ts
  src/functions/unreferencedReusableObject.ts
  src/resolved.ts
  src/rulesets/oas/functions/refSiblings.ts
  src/spectral.ts
  src/utils/__tests__/refs.jest.test.ts
  src/utils/hasRef.ts
  src/utils/index.ts
  src/utils/refs.ts
  yarn.lock
Labels: bug

#840 feat: report invalid YAML mapping keys
  package.json
  src/__tests__/linter.test.ts
  test-harness/scenarios/enabled-rules-amount.oas3.scenario
  test-harness/scenarios/parameter-description-links.oas3.scenario
  test-harness/scenarios/parameter-description-parameters.oas2.scenario
  test-harness/scenarios/parameter-description-parameters.oas3.scenario
  test-harness/scenarios/severity/fail-on-error-no-error.scenario
  test-harness/scenarios/severity/fail-on-error.oas3.scenario
  yarn.lock
Labels: enhancement

#850 fix: use non-secure version of nanoid
  src/rulesets/__tests__/reader.jest.test.ts
  src/rulesets/mergers/__tests__/functions.jest.test.ts
  src/rulesets/mergers/functions.ts
Labels: bug

#798 feat: report unrecognized formats
  docs/guides/cli.md
  src/__tests__/linter.jest.test.ts
  src/__tests__/linter.test.ts
  src/cli/commands/__tests__/lint.test.ts
  src/cli/commands/lint.ts
  src/cli/services/linter/linter.ts
  src/spectral.ts
  src/types/config.ts
  src/types/spectral.ts
  test-harness/scenarios/custom-ref-resolver.scenario
  test-harness/scenarios/help-no-document.scenario
  test-harness/scenarios/ignored-unrecognized-format.scenario
  test-harness/scenarios/proxy-agent.scenario
  test-harness/scenarios/rules-matching-multiple-places.scenario
  test-harness/scenarios/unrecognized-format.scenario
Labels: enhancement

#861 build: disable auto-merge for dependabot
  .github/workflows/automerge.yml
Labels: chore

#839 fix: absolute paths
  src/__tests__/linter.jest.test.ts
  src/__tests__/spectral.jest.test.ts
  src/__tests__/spectral.test.ts
  src/cli/services/__tests__/linter.test.ts
  src/linter.ts
  src/resolved.ts
  src/rulesets/__tests__/message.spec.ts
  src/rulesets/message.ts
  src/utils/refs.ts
Labels: automerge, bug

#856 feat: dedupe results by unique fingerprint
  docs/guides/javascript.md
  package.json
  src/__tests__/linter.jest.test.ts
  src/__tests__/linter.test.ts
  src/__tests__/spectral.jest.test.ts
  src/cli/services/linter/linter.ts
  src/cli/services/linter/utils/deduplicateResults.ts
  src/cli/services/linter/utils/index.ts
  src/formatters/__tests__/html.test.ts
  src/formatters/__tests__/json.test.ts
  src/formatters/__tests__/junit.test.ts
  src/formatters/__tests__/stylish.test.ts
  src/formatters/__tests__/teamcity.test.ts
  src/formatters/__tests__/text.test.ts
  src/formatters/html/index.ts
  src/formatters/stylish.ts
  src/formatters/teamcity.ts
  src/formatters/text.ts
  src/formatters/utils/index.ts
  src/rulesets/oas/__tests__/contact-properties.ts
  src/rulesets/oas/functions/__tests__/oasOpParams.test.ts
  src/spectral.ts
  src/types/spectral.ts
  src/utils/__tests__/__fixtures__/duplicate-validation-results.json
  src/utils/__tests__/prepareResults.spec.ts
  src/utils/__tests__/sortResults.test.ts
  src/utils/index.ts
  src/utils/prepareResults.ts
  src/utils/sortResults.ts
  yarn.lock
Labels: automerge

#869 feat: switch default from warn to error
  CHANGELOG.md
  docs/guides/cli.md
  src/cli/commands/lint.ts
Labels: automerge

#873 test: warn -> error
  test-harness/scenarios/custom-ref-resolver.scenario
  test-harness/scenarios/help-no-document.scenario
  test-harness/scenarios/ignored-unrecognized-format.scenario
  test-harness/scenarios/parameter-description-links.oas3.scenario
  test-harness/scenarios/valid-no-errors.oas2.scenario
Labels: automerge, chore

#867 feat: consistent paths in messages
  src/__tests__/linter.jest.test.ts
  src/__tests__/linter.test.ts
  src/cli/services/__tests__/linter.test.ts
  src/formatters/junit.ts
  src/functions/__tests__/falsy.test.ts
  src/functions/__tests__/schema-path.test.ts
  src/functions/__tests__/schema.test.ts
  src/functions/__tests__/truthy.test.ts
  src/functions/falsy.ts
  src/functions/schema-path.ts
  src/functions/schema.ts
  src/functions/truthy.ts
  src/functions/undefined.ts
  src/linter.ts
  src/rulesets/__tests__/message.spec.ts
  src/rulesets/message.ts
  src/rulesets/oas/__tests__/oas2-schema.ts
  src/rulesets/oas/__tests__/oas2-valid-definition-example.ts
  src/rulesets/oas/__tests__/oas2-valid-parameter-example.ts
  src/rulesets/oas/__tests__/oas3-valid-oas-parameter-example.ts
  src/rulesets/oas/__tests__/oas3-valid-parameter-schema-example.ts
  src/rulesets/oas/__tests__/oas3-valid-schema-example.ts
  src/rulesets/oas/__tests__/templates/_oas-example.ts
  src/rulesets/oas/__tests__/templates/_schema-example.ts
  src/utils/__tests__/printPath.spec.ts
  src/utils/__tests__/replacer.spec.ts
  src/utils/index.ts
  src/utils/printPath.ts
  src/utils/replacer.ts
  test-harness/scenarios/external-schemas-ruleset.scenario
  test-harness/scenarios/results-format-junit.oas3.scenario
  test-harness/scenarios/rules-matching-multiple-places.scenario
Labels: enhancement
