Repository stoplightio/spectral, pull requests merged in 2019-10, with the labels that each got.

#615 fix(resolving): detect the source of local references properly
  src/__tests__/spectral.test.ts
  src/cli/services/__tests__/__fixtures__/draft-nested-ref.oas2.json
  src/cli/services/__tests__/__fixtures__/refs/paths.json
  src/cli/services/__tests__/linter.test.ts
  src/linter.ts
  src/resolved.ts
  src/rulesets/oas/functions/refSiblings.ts
  src/utils/hasRef.ts
  src/utils/index.ts
Labels: bug

#621 fix(junit): make formatter more spec-compliant
  src/formatters/__tests__/junit.test.ts
  src/formatters/junit.ts
  test-harness/scenarios/results-format-junit.oas3.scenario
Labels: bug

#616 feat: accept multiple paths
  package.json
  src/cli/commands/__tests__/lint.test.ts
  src/cli/commands/lint.ts
  src/cli/services/__tests__/linter.test.ts
  src/cli/services/linter.ts
  src/cli/services/linter/index.ts
  src/cli/services/linter/linter.ts
  src/cli/services/linter/utils/getRuleset.ts
  src/cli/services/linter/utils/index.ts
  src/cli/services/linter/utils/listFiles.ts
  src/cli/services/linter/utils/skipRules.ts
  test-harness/scenarios/enabled-rules-amount.oas3.scenario
  test-harness/scenarios/help-no-document.scenario
  yarn.lock
Labels: enhancement

#628 docs(cli): expose multiple paths
  docs/guides/cli.md
  docs/guides/workflows.md
Labels: documentation

#622 feat(rule): expose {{value}} and {{path}} for use in messages
  src/__tests__/linter.jest.test.ts
  src/__tests__/linter.test.ts
  src/linter.ts
  src/resolved.ts
  src/rulesets/message.ts
  src/rulesets/oas/__tests__/message.spec.ts
Labels: enhancement

#648 chore(deps): remove @types/yaml
  package.json
  yarn.lock
Labels: dependencies

#652 feat(ruleset): make rules optional
  src/meta/ruleset.schema.json
  src/rulesets/__tests__/__fixtures__/extends-only-ruleset.json
  src/rulesets/__tests__/reader.jest.test.ts
  src/rulesets/__tests__/validation.test.ts
  src/rulesets/reader.ts
  src/rulesets/validation.ts
  src/types/ruleset.ts
Labels: enhancement

#666 chore: remove @oclif/test leftovers
  src/rulesets/oas2/__tests__/valid-example-in-definitions.ts
  src/rulesets/oas2/__tests__/valid-example-in-parameters.ts
  src/rulesets/oas3/__tests__/templates/_oas-example.ts
  src/rulesets/oas3/__tests__/templates/_schema-example.ts
  src/rulesets/oas3/__tests__/valid-example-in-schemas.ts
  src/rulesets/oas3/__tests__/valid-oas-example-in-parameters.ts
  src/rulesets/oas3/__tests__/valid-schema-example-in-parameters.ts
Labels: chore

#668 docs(changelog): release 4.2
  CHANGELOG.md
Labels: documentation

#667 chore(tests): raise tests execution timeout to 10s
  setupJest.ts
Labels: chore

#653 chore(karma): improve fixtures generation
  .gitignore
  scripts/generate-karma-fixtures.js
  setupKarma.ts
Labels: chore

#649 chore: keep the indentation style homogeneous accross IDEs
  .editorconfig
Labels: chore

#665 chore: drop support for Node 8
  .circleci/config.yml
  package.json
  tsconfig.json
Labels: breaking

#635 Detect unused OAS2 definitions and OAS3 component schemas
  docs/reference/functions.md
  docs/reference/openapi-rules.md
  package.json
  rollup.config.js
  src/__tests__/linter.test.ts
  src/functions/__tests__/alphabetical.test.ts
  src/functions/__tests__/enum.test.ts
  src/functions/__tests__/falsy.test.ts
  src/functions/__tests__/pattern.test.ts
  src/functions/__tests__/schema-path.test.ts
  src/functions/__tests__/schema.test.ts
  src/functions/__tests__/truthy.test.ts
  src/functions/__tests__/unreferencedReusableObject.ts
  src/functions/index.ts
  src/functions/unreferencedReusableObject.ts
  src/linter.ts
  src/resolved.ts
  src/rulesets/__tests__/__fixtures__/unusedComponentsSchema.definition.json
  src/rulesets/__tests__/__fixtures__/unusedComponentsSchema.indirect.1.json
  src/rulesets/__tests__/__fixtures__/unusedComponentsSchema.indirect.2.json
  src/rulesets/__tests__/__fixtures__/unusedComponentsSchema.remoteLocal.json
  src/rulesets/__tests__/__fixtures__/unusedDefinition.definition.json
  src/rulesets/__tests__/__fixtures__/unusedDefinition.indirect.1.json
  src/rulesets/__tests__/__fixtures__/unusedDefinition.indirect.2.json
  src/rulesets/__tests__/__fixtures__/unusedDefinition.remoteLocal.json
  src/rulesets/__tests__/validation.test.ts
  src/rulesets/oas2/__tests__/unusedDefinition.jest.test.ts
  src/rulesets/oas2/__tests__/unusedDefinition.karma.test.ts
  src/rulesets/oas2/__tests__/unusedDefinition.test.ts
  src/rulesets/oas2/index.json
  src/rulesets/oas3/__tests__/unusedComponentsSchema.jest.test.ts
  src/rulesets/oas3/__tests__/unusedComponentsSchema.karma.test.ts
  src/rulesets/oas3/__tests__/unusedComponentsSchema.test.ts
  src/rulesets/oas3/index.json
  src/types/function.ts
  test-harness/scenarios/enabled-rules-amount.oas3.scenario
  yarn.lock
Labels: enhancement

#682 chore: Bump @stoplight/json-ref-resolver from 2.4.1 to 3.0.1
  package.json
  src/__tests__/spectral.test.ts
  src/resolved.ts
  yarn.lock
Labels: dependencies

#676 chore: minor JSONSchema typings tweak
  src/formats/json-schema.ts
  src/functions/schema.ts
  src/rulesets/evaluators.ts
  src/rulesets/reader.ts
  src/rulesets/validation.ts
  src/types/ruleset.ts
  src/types/spectral.ts
Labels: chore

#614 feat(rule): remove 'when'
  src/__tests__/linter.test.ts
  src/linter.ts
  src/meta/rule.schema.json
  src/types/rule.ts
Labels: breaking, tech-debt

#706 breaking: bump default fail severity to warn
  .circleci/config.yml
  CHANGELOG.md
  docs/guides/cli.md
  src/__tests__/linter.test.ts
  src/cli/commands/lint.ts
  src/cli/services/__tests__/__fixtures__/openapi-3.0-valid.yaml
  src/cli/services/__tests__/linter.test.ts
  src/rulesets/oas/index.json
  test-harness/scenarios/help-no-document.scenario
  test-harness/scenarios/parameter-description-links.oas3.scenario
  test-harness/scenarios/results-default-format-json-quiet.oas3.scenario
  test-harness/scenarios/results-default-format-json.oas3.scenario
  test-harness/scenarios/results-default-output.oas3.scenario
  test-harness/scenarios/results-default.oas3.scenario
  test-harness/scenarios/results-format-stylish.oas3.scenario
  test-harness/scenarios/results-skip-rule.oas3.scenario
  test-harness/scenarios/results-skip-rules-multiple.oas3.scenario
  test-harness/scenarios/severity/display-warnings.oas3.scenario
  test-harness/scenarios/severity/fail-on-error-no-error.scenario
  test-harness/scenarios/severity/fail-on-error.oas3.scenario
  test-harness/scenarios/severity/stylish-display-proper-names.scenario
  test-harness/scenarios/valid-no-errors.oas2.scenario
Labels: breaking, enhancement

#671 feat: static assets
  package.json
  rollup.config.js
  scripts/compile-rulesets.js
  scripts/generate-assets.js
  src/assets.ts
  src/fs/reader.ts
  src/rulesets/__tests__/reader.jest.test.ts
  src/rulesets/__tests__/reader.karma.test.ts
  src/rulesets/finder.ts
  src/rulesets/map.ts
  src/spectral.ts
  src/utils/empty.ts
  src/utils/index.ts
Labels: enhancement

#711 chore: remove addRules and addFunctions
  docs/getting-started/rulesets.md
  docs/guides/javascript.md
  docs/migration-guides/5.0.md
  src/rulesets/oas/index.ts
  src/rulesets/oas2/index.ts
  src/rulesets/oas3/index.ts
  src/spectral.ts
Labels: breaking, chore

#719 feat: rules are recommended by default
  docs/getting-started/rulesets.md
  setupKarma.ts
  src/__tests__/spectral.jest.test.ts
  src/__tests__/spectral.karma.test.ts
  src/cli/services/__tests__/output.test.ts
  src/rulesets/__tests__/reader.jest.test.ts
  src/rulesets/mergers/__tests__/rules.jest.test.ts
  src/rulesets/mergers/rules.ts
  src/rulesets/severity.ts
  src/types/rule.ts
Labels: breaking, enhancement
