Repository stoplightio/spectral, pull requests merged in 2019-09, with the labels that each got.

#528 docs(changelog): 4.1.1 release
  CHANGELOG.md
Labels: documentation

#515 Do not validate description in parameters for links
  docs/reference/openapi-rules.md
  src/rulesets/__tests__/shared/_parameter-description.ts
  src/rulesets/oas/index.json
  src/rulesets/oas2/__tests__/oas2-parameter-description.ts
  src/rulesets/oas2/index.json
  src/rulesets/oas3/__tests__/oas3-parameter-description.ts
  src/rulesets/oas3/index.json
  test-harness/scenarios/parameter-description-links.oas3.scenario
  test-harness/scenarios/parameter-description-parameters.oas2.scenario
  test-harness/scenarios/parameter-description-parameters.oas3.scenario
  test-harness/scenarios/rulesets/parameter-description.oas2.yaml
  test-harness/scenarios/rulesets/parameter-description.oas3.yaml
Labels: bug

#519 feat: implement JUnit formatter
  README.md
  karma.conf.ts
  package.json
  src/cli/commands/lint.ts
  src/cli/services/output.ts
  src/formatters/__tests__/__fixtures__/oas3-schema-errors.json
  src/formatters/__tests__/junit.test.ts
  src/formatters/__tests__/stylish.test.ts
  src/formatters/index.ts
  src/formatters/json.ts
  src/formatters/junit.ts
  src/formatters/stylish.ts
  src/formatters/types.ts
  src/formatters/utils/groupBySource.ts
  src/formatters/utils/sortResults.ts
  src/formatters/utils/xmlEscape.ts
  src/types/config.ts
  test-harness/index.ts
  test-harness/scenarios/results-format-junit.oas3.scenario
  yarn.lock
Labels: enhancement

#562 fix(resolving): persist parseMap until resolver cache instance is gone
  src/__tests__/spectral.test.ts
  src/rulesets/__tests__/reader.jest.test.ts
  src/spectral.ts
Labels: enhancement

#563 chore: switch to npm version of better-ajv-errors
  package.json
  yarn.lock
Labels: dependencies

#569 fix(stylish): support hint and print proper severity
  src/formatters/__tests__/__fixtures__/mixed-errors.json
  src/formatters/__tests__/__fixtures__/oas3-schema-errors.json
  src/formatters/__tests__/stylish.test.ts
  src/formatters/stylish.ts
  src/formatters/utils/getHighestSeverity.ts
  src/formatters/utils/groupBySeverity.ts
  test-harness/scenarios/parameter-description-parameters.oas2.scenario
  test-harness/scenarios/parameter-description-parameters.oas3.scenario
  test-harness/scenarios/results-default-output.oas3.scenario
  test-harness/scenarios/results-default.oas3.scenario
  test-harness/scenarios/results-format-stylish.oas3.scenario
  test-harness/scenarios/results-skip-rule.oas3.scenario
  test-harness/scenarios/results-skip-rules-multiple.oas3.scenario
  test-harness/scenarios/rulesets/oas-mixed-severity.json
  test-harness/scenarios/severity/display-warnings.oas3.scenario
  test-harness/scenarios/severity/fail-on-error-no-error.scenario
  test-harness/scenarios/severity/fail-on-error.oas3.scenario
  test-harness/scenarios/severity/stylish-display-proper-names.scenario
Labels: bug

#576 fix(schema): support draft 6 and 7
  src/functions/__tests__/schema.test.ts
  src/functions/schema.ts
  test-harness/scenarios/external-schemas-ruleset.scenario
  test-harness/scenarios/rulesets/external-schemas-ruleset.yaml
  test-harness/scenarios/rulesets/schemas/foo-description.yaml
  test-harness/scenarios/rulesets/schemas/stoplight-title.yaml
Labels: bug

#575 feat: introduce json-schema format
  docs/getting-started/rulesets.md
  src/__tests__/linter.jest.test.ts
  src/__tests__/linter.test.ts
  src/__tests__/spectral.jest.test.ts
  src/cli/services/linter.ts
  src/formats/__tests__/json-schema.spec.ts
  src/formats/__tests__/openapi.spec.ts
  src/formats/index.ts
  src/formats/json-schema.ts
  src/formats/openapi.ts
  src/index.ts
  src/rulesets/evaluators.ts
  src/utils/isObject.ts
  test-harness/scenarios/rulesets/loose-schema-ruleset.json
  test-harness/scenarios/todo-full-loose-schema.scenario
Labels: enhancement

#581 feat: let multiple formats to be matched
  docs/getting-started/rulesets.md
  src/__tests__/linter.test.ts
  src/resolved.ts
  src/runner.ts
  src/spectral.ts
  src/types/spectral.ts
  src/utils/__tests__/hasIntersectingElement.spec.ts
  src/utils/hasIntersectingElement.ts
  src/utils/index.ts
Labels: enhancement

#579 feat(schema): improve enum validation
  package.json
  src/functions/__tests__/schema.test.ts
  src/functions/schema.ts
  test-harness/scenarios/external-schemas-ruleset.scenario
  yarn.lock
Labels: enhancement

#580 fix(request): proxy-agent breaks Studio
  src/__tests__/request.jest.test.ts
  src/cli/index.ts
  src/fs/reader.ts
  src/request.ts
  test-harness/helpers.ts
  test-harness/index.ts
  test-harness/scenarios/proxy-agent.scenario
Labels: bug

#587 feat(cli): display the amount of enabled rules
  src/cli/services/linter.ts
  src/runner.ts
  test-harness/scenarios/enabled-rules-amount.oas3.scenario
Labels: enhancement

#595 chore(deps): remove unused yaml package
  package.json
  yarn.lock
Labels: dependencies

#588 feat(junit): include property path
  src/formatters/__tests__/__fixtures__/mixed-errors-with-different-paths.json
  src/formatters/__tests__/junit.test.ts
  src/formatters/junit.ts
  test-harness/scenarios/results-format-junit.oas3.scenario
Labels: enhancement

#613 feat(alphabetical): improve validation results
  src/functions/__tests__/alphabetical.test.ts
  src/functions/alphabetical.ts
Labels: enhancement
