Repository stoplightio/spectral, pull requests merged in 2019-11, with the labels that each got.

#740 fix: unixify glob patterns
  src/cli/services/__tests__/linter.test.ts
  src/cli/services/linter/utils/__tests__/listFiles.spec.ts
  src/cli/services/linter/utils/listFiles.ts
Labels: bug

#739 chore: Upgrade to typescript 3.7.2
  package.json
  src/__tests__/spectral.jest.test.ts
  src/__tests__/spectral.test.ts
  src/rulesets/__tests__/reader.jest.test.ts
  yarn.lock
Labels: dependencies

#749 test: stub fast-glob more properly
  src/cli/services/linter/utils/__tests__/listFiles.spec.ts
Labels: chore

#681 fix(cli): do not return duplicate results
  src/cli/services/linter/linter.ts
  src/cli/services/linter/utils/__tests__/__fixtures__/duplicate-validation-results.json
  src/cli/services/linter/utils/__tests__/deduplicateResults.spec.ts
  src/cli/services/linter/utils/deduplicateResults.ts
  src/cli/services/linter/utils/index.ts
  src/runner.ts
Labels: bug

#712 feat: casing function
  docs/reference/functions.md
  src/functions/__tests__/casing.test.ts
  src/functions/__tests__/unreferencedReusableObject.test.ts
  src/functions/casing.ts
  src/functions/index.ts
  src/types/enums.ts
  src/types/rule.ts
Labels: enhancement

#790 docs: describe custom resolver usage
  docs/guides/javascript.md
Labels: documentation

#723 fix: inheritance of rule with implicit severity and a few extra tests covering inheritance
  src/rulesets/__tests__/__fixtures__/inheritanceRulesets/my-ruleset-recommended.json
  src/rulesets/__tests__/__fixtures__/inheritanceRulesets/my-ruleset.json
  src/rulesets/__tests__/__fixtures__/inheritanceRulesets/ruleset-a.json
  src/rulesets/__tests__/__fixtures__/inheritanceRulesets/ruleset-b.json
  src/rulesets/__tests__/__fixtures__/inheritanceRulesets/ruleset-c.json
  src/rulesets/__tests__/reader.jest.test.ts
  src/rulesets/__tests__/rule-name-conflicts.jest.test.ts
  src/rulesets/mergers/__tests__/rules.jest.test.ts
  src/rulesets/mergers/rules.ts
Labels: chore

#792 fix: binary install was broken for linux
  .github/workflows/automerge.yml
  scripts/install.sh
  yarn.lock
Labels: automerge

#758 feat(cli): accept stdin
  src/cli/commands/__tests__/lint.test.ts
  src/cli/commands/lint.ts
  src/cli/services/linter/linter.ts
  src/cli/services/linter/utils/listFiles.ts
  src/fs/__tests__/__fixtures__/simple
  src/fs/__tests__/reader.jest.test.ts
  src/fs/reader.ts
  test-harness/scenarios/help-no-document.scenario
  test-harness/scenarios/stdin-document-with-errors.scenario
  test-harness/scenarios/stdin.scenario
Labels: enhancement

#795 revert: install.sh download urls
  scripts/install.sh
Labels: automerge

#796 chore(test-harness): update readme
  test-harness/README.md
  test-harness/index.ts
  test-harness/scenarios/enabled-rules-amount.oas3.scenario
  test-harness/scenarios/external-schemas-ruleset.scenario
  test-harness/scenarios/help-no-document.scenario
  test-harness/scenarios/parameter-description-links.oas3.scenario
  test-harness/scenarios/parameter-description-parameters.oas2.scenario
  test-harness/scenarios/parameter-description-parameters.oas3.scenario
  test-harness/scenarios/proxy-agent.scenario
  test-harness/scenarios/results-default-format-json-quiet.oas3.scenario
  test-harness/scenarios/results-default-format-json.oas3.scenario
  test-harness/scenarios/results-default-output.oas3.scenario
  test-harness/scenarios/results-default.oas3.scenario
  test-harness/scenarios/results-format-junit.oas3.scenario
  test-harness/scenarios/results-format-stylish.oas3.scenario
  test-harness/scenarios/results-skip-rule.oas3.scenario
  test-harness/scenarios/results-skip-rules-multiple.oas3.scenario
  test-harness/scenarios/severity/display-errors.oas3.scenario
  test-harness/scenarios/severity/display-warnings.oas3.scenario
  test-harness/scenarios/severity/fail-on-error-no-error.scenario
  test-harness/scenarios/severity/fail-on-error.oas3.scenario
  test-harness/scenarios/severity/stylish-display-proper-names.scenario
  test-harness/scenarios/stdin-document-with-errors.scenario
  test-harness/scenarios/stdin.scenario
  test-harness/scenarios/todo-full-loose-schema.scenario
  test-harness/scenarios/valid-no-errors.oas2.scenario
Labels: automerge, chore

#799 feat: arrayish given
  .editorconfig
  docs/getting-started/rulesets.md
  src/__tests__/linter.test.ts
  src/linter.ts
  src/meta/rule.schema.json
  src/runner.ts
  src/types/rule.ts
  test-harness/scenarios/rules-matching-multiple-places.scenario
Labels: enhancement

#813 docs: clarify custom functions and rule messages
  docs/getting-started/rulesets.md
  docs/guides/custom-functions.md
Labels: automerge, documentation

#807 feat(cli): implement HTML formatter
  README.md
  package.json
  src/cli/services/output.ts
  src/formatters/__tests__/html.test.ts
  src/formatters/html/html-template-message.html
  src/formatters/html/html-template-page.html
  src/formatters/html/html-template-result.html
  src/formatters/html/index.ts
  src/formatters/index.ts
  src/formatters/stylish.ts
  src/formatters/utils/__tests__/sortResults.test.ts
  src/formatters/utils/getColorForSeverity.ts
  src/formatters/utils/getSeverityName.ts
  src/formatters/utils/getSummary.ts
  src/formatters/utils/index.ts
  src/formatters/utils/pluralize.ts
  src/types/config.ts
  test-harness/index.ts
  test-harness/scenarios/results-format-html.oas3.scenario
  yarn.lock
Labels: automerge, enhancement

#814 docs: update Spectral JS API usage
  .editorconfig
  docs/guides/javascript.md
Labels: automerge, documentation

#797 feat(cli): implement --resolver flag
  docs/guides/cli.md
  src/cli/commands/__tests__/lint.test.ts
  src/cli/commands/lint.ts
  src/cli/services/__tests__/__fixtures__/foo-document.yaml
  src/cli/services/__tests__/__fixtures__/foo-resolver.js
  src/cli/services/__tests__/linter.test.ts
  src/cli/services/linter/linter.ts
  src/cli/services/linter/utils/__tests__/__fixtures__/resolver.js
  src/cli/services/linter/utils/__tests__/getResolver.spec.ts
  src/cli/services/linter/utils/getResolver.ts
  src/types/config.ts
  test-harness/index.ts
  test-harness/scenarios/custom-ref-resolver.scenario
  test-harness/scenarios/help-no-document.scenario
  test-harness/scenarios/invalid-custom-ref-resolver.scenario
  test-harness/scenarios/resolvers/custom.js
Labels: enhancement
