Repository stoplightio/spectral, pull requests merged in 2020-09, with the labels that each got.

#1331 Fixed section title
  docs/guides/4-custom-rulesets.md
Labels: documentation

#1317 chore(deps): bump @stoplight/lifecycle
  package.json
  src/runner/runtime.ts
  yarn.lock
Labels: chore

#1332 feat(ruleset): support YAML merge keys
  src/rulesets/__tests__/__fixtures__/ruleset-with-merge-keys.yaml
  src/rulesets/__tests__/reader.jest.test.ts
  src/rulesets/reader.ts
Labels: enhancement

#1337 build(circleci): use matrix jobs
  .circleci/config.yml
  package.json
Labels: chore

#1338 feat: implement defined function
  docs/reference/functions.md
  src/functions/__tests__/defined.test.ts
  src/functions/defined.ts
Labels: enhancement

#1313 feat(oas): merge example rules
  src/rulesets/oas/__tests__/oas2-valid-definition-example.ts
  src/rulesets/oas/__tests__/oas2-valid-media-example.ts
  src/rulesets/oas/__tests__/oas2-valid-parameter-example.ts
  src/rulesets/oas/__tests__/oas2-valid-response-example.ts
  src/rulesets/oas/__tests__/oas2-valid-schema-example.ts
  src/rulesets/oas/__tests__/oas3-valid-header-schema-example.ts
  src/rulesets/oas/__tests__/oas3-valid-media-example.test.ts
  src/rulesets/oas/__tests__/oas3-valid-oas-content-example.ts
  src/rulesets/oas/__tests__/oas3-valid-oas-header-example.ts
  src/rulesets/oas/__tests__/oas3-valid-oas-parameter-example.ts
  src/rulesets/oas/__tests__/oas3-valid-parameter-schema-example.ts
  src/rulesets/oas/__tests__/oas3-valid-schema-example.ts
  src/rulesets/oas/__tests__/templates/_oas-example.ts
  src/rulesets/oas/__tests__/templates/_schema-example.ts
  src/rulesets/oas/__tests__/valid-example.test.ts
  src/rulesets/oas/index.json
  test-harness/scenarios/enabled-rules-amount.oas3.scenario
  test-harness/scenarios/examples.oas2.scenario
  test-harness/scenarios/examples.oas3.scenario
  test-harness/scenarios/oas2-valid-media-example.oas2.scenario
Labels: breaking, enhancement

#1341 feat(replacer): allow code to be evaluated
  package.json
  src/__tests__/linter.jest.test.ts
  src/__tests__/linter.test.ts
  src/functions/__tests__/defined.test.ts
  src/functions/__tests__/falsy.test.ts
  src/functions/__tests__/schemaPath.test.ts
  src/functions/__tests__/truthy.test.ts
  src/functions/defined.ts
  src/functions/falsy.ts
  src/functions/schema.ts
  src/functions/truthy.ts
  src/functions/undefined.ts
  src/rulesets/__tests__/message.test.ts
  src/rulesets/message.ts
  src/utils/__tests__/replacer.test.ts
  src/utils/replacer.ts
  yarn.lock
Labels: enhancement

#1355 docs: move Spectral banner under docs/img
  README.md
  docs/img/spectral-banner.png
Labels: documentation
