Repository stoplightio/spectral, pull requests merged in 2020-11, with the labels that each got.

#1383 docs(changelog): release 5.7
  CHANGELOG.md
Labels: documentation

#1390 fix: expose defined function
  src/functions/index.ts
Labels: bug

#1401 chore: files cleanup
  .eslintrc
  __karma__/jest.ts
  karma.conf.ts
  package.json
  rollup.config.js
  test-harness/jest.config.js
  tsconfig.build.json
  tsconfig.eslint.json
  tsconfig.json
  tsconfig.karma.json
  tsconfig.rollup.json
Labels: chore

#1358 test: reduce reliance on oas rulesets
  src/__tests__/__fixtures__/custom-oas-ruleset.json
  src/__tests__/__fixtures__/rulesets/bare.json
  src/__tests__/__fixtures__/rulesets/custom-directory-function.json
  src/__tests__/__fixtures__/rulesets/custom-functions.json
  src/__tests__/__fixtures__/rulesets/customFunctions/hasIn.js
  src/__tests__/__fixtures__/rulesets/exceptions-resolving.json
  src/__tests__/__fixtures__/rulesets/exceptions.json
  src/__tests__/__fixtures__/rulesets/functions/deepHasIn.js
  src/__tests__/__fixtures__/rulesets/functions/hasIn.js
  src/__tests__/__fixtures__/rulesets/functions/truthy.js
  src/__tests__/__fixtures__/rulesets/functions/validateBar.js
  src/__tests__/__fixtures__/rulesets/recommended.json
  src/__tests__/linter.jest.test.ts
  src/__tests__/linter.test.ts
  src/__tests__/spectral.jest.test.ts
Labels: chore

#1395 fix: use correct documentation urls
  src/rulesets/__tests__/reader.jest.test.ts
  src/rulesets/asyncapi/index.json
  src/rulesets/oas/index.json
  src/rulesets/reader.ts
Labels: bug

#1382 feat: Add JSON path to stylish formatter
  src/cli/formatters/__tests__/stylish.test.ts
  src/cli/formatters/stylish.ts
  test-harness/scenarios/alphabetical-responses-order.oas3.scenario
  test-harness/scenarios/asyncapi2-streetlights.scenario
  test-harness/scenarios/custom-function-can-return-multiple-results.scenario
  test-harness/scenarios/enabled-rules-amount.oas3.scenario
  test-harness/scenarios/examples.oas2.scenario
  test-harness/scenarios/examples.oas3.scenario
  test-harness/scenarios/exceptions.circular.reference.oas3.scenario
  test-harness/scenarios/exceptions.circular.silenced.oas3.scenario
  test-harness/scenarios/exceptions.oas3.scenario
  test-harness/scenarios/exceptions.oas3.stdin.scenario
  test-harness/scenarios/external-schemas-ruleset.scenario
  test-harness/scenarios/oas2-valid-media-example.oas2.scenario
  test-harness/scenarios/oas3-schema.scenario
  test-harness/scenarios/parameter-description-parameters.oas2.scenario
  test-harness/scenarios/parameter-description-parameters.oas3.scenario
  test-harness/scenarios/proxy-agent.scenario
  test-harness/scenarios/results-default-output.oas3.scenario
  test-harness/scenarios/results-default.oas3.scenario
  test-harness/scenarios/results-format-stylish.oas3.scenario
  test-harness/scenarios/results-skip-rule.oas3.scenario
  test-harness/scenarios/rules-matching-multiple-places.scenario
  test-harness/scenarios/severity/display-warnings.oas3.scenario
  test-harness/scenarios/severity/fail-on-error-no-error.scenario
  test-harness/scenarios/severity/fail-on-error.oas3.scenario
  test-harness/scenarios/severity/stylish-display-proper-names.scenario
  test-harness/scenarios/stdin-document-with-errors.scenario
  test-harness/scenarios/stdin.scenario
  test-harness/scenarios/todo-full-loose-schema.scenario
  test-harness/scenarios/typed-enum.oas3.scenario
Labels: enhancement

#1405 feat(ruleset): optional pointer for exceptions
  docs/guides/6-exceptions.md
  src/__tests__/__fixtures__/rulesets/exceptions-resolving.json
  src/__tests__/linter.jest.test.ts
  src/rulesets/__tests__/__fixtures__/exceptions/invalid.yaml
  src/rulesets/mergers/__tests__/exceptions.test.ts
  src/rulesets/mergers/exceptions.ts
  src/runner/utils/__tests__/pivotExceptions.test.ts
  src/runner/utils/isAKnownException.ts
  src/runner/utils/pivotExceptions.ts
Labels: enhancement

#1362 chore: improve OAS functions
  src/rulesets/oas/functions/__tests__/oasOpIdUnique.test.ts
  src/rulesets/oas/functions/oasExample.ts
  src/rulesets/oas/functions/oasOpFormDataConsumeCheck.ts
  src/rulesets/oas/functions/oasOpIdUnique.ts
  src/rulesets/oas/functions/oasOpSecurityDefined.ts
  src/rulesets/oas/functions/oasOpSuccessResponse.ts
  src/rulesets/oas/functions/oasTagDefined.ts
  src/rulesets/oas/functions/utils/getAllOperations.ts
  src/rulesets/oas/functions/utils/isObject.ts
  test-harness/scenarios/severity/fail-on-error.oas3.scenario
Labels: bug
