Repository stoplightio/spectral, pull requests merged in 2020-04, with the labels that each got.

#1050 docs: identify the schema used for Yaml 1.2 tag resolution
  docs/guides/javascript.md
Labels: documentation

#1051 chore: migrate typed-enum function
  src/functions/index.ts
  src/rulesets/oas/__tests__/typed-enum.ts
  src/rulesets/oas/functions/__tests__/typedEnum.test.ts
  src/rulesets/oas/functions/typedEnum.ts
  src/rulesets/oas/index.json
  src/types/rule.ts
  tsconfig.rollup.json
Labels: chore

#1053 docs(changelog): 5.3 release
  CHANGELOG.md
Labels: documentation

#1052 chore(deps): remove unmaintained Rollup deps
  package.json
  rollup.config.js
  yarn.lock
Labels: dependencies

#1059 fix: make `example-value-or-externalValue` only target oas3 document
  docs/reference/functions.md
  docs/reference/openapi-rules.md
  src/rulesets/oas/__tests__/oas3-example-value-or-externalValue.ts
  src/rulesets/oas/index.json
Labels: bug

#1075 fix: use fs.stat in favor of fs.access
  src/cli/services/__tests__/linter.test.ts
  src/rulesets/__tests__/finder.jest.test.ts
  src/rulesets/finder.ts
Labels: bug

#1078 feat: expose cache to custom functions
  docs/guides/custom-functions.md
  src/__tests__/linter.jest.test.ts
  src/spectral.ts
  src/types/function.ts
Labels: enhancement

#1071 fix: improve schema validation
  src/__tests__/linter.jest.test.ts
  src/__tests__/linter.test.ts
  src/cli/services/__tests__/__fixtures__/draft-ref.oas2.json
  src/cli/services/__tests__/linter.test.ts
  src/functions/__tests__/schema-path.test.ts
  src/functions/__tests__/schema.test.ts
  src/functions/schema.ts
  src/rulesets/message.ts
  src/rulesets/oas/__tests__/oas2-schema.ts
  src/rulesets/oas/__tests__/oas2-valid-definition-example.ts
  src/rulesets/oas/__tests__/oas2-valid-parameter-example.ts
  src/rulesets/oas/__tests__/oas3-valid-oas-parameter-example.ts
  src/rulesets/oas/__tests__/oas3-valid-parameter-schema-example.ts
  src/rulesets/oas/__tests__/oas3-valid-schema-example.ts
  src/rulesets/oas/__tests__/templates/_oas-example.ts
  src/rulesets/oas/__tests__/templates/_schema-example.ts
  src/rulesets/oas/functions/__tests__/oasDocumentSchema.test.ts
  src/rulesets/oas/functions/oasDocumentSchema.ts
  src/rulesets/oas/index.json
  test-harness/scenarios/external-schemas-ruleset.scenario
  test-harness/scenarios/oas3-schema.scenario
  test-harness/scenarios/results-format-junit.oas3.scenario
Labels: bug

#1079 feat: expose fetch to custom functions
  src/__tests__/linter.jest.test.ts
  src/__tests__/linter.karma.test.ts
  src/rulesets/__tests__/evaluators.test.ts
  src/rulesets/evaluators.ts
  src/spectral.ts
Labels: enhancement

#1093 fix(rulesets): load custom functions from npm
  docs/getting-started/rulesets.md
  src/rulesets/__tests__/__fixtures__/ruleset-extends-npm-versioned.json
  src/rulesets/__tests__/__fixtures__/ruleset-extends-npm.json
  src/rulesets/__tests__/reader.jest.test.ts
  src/rulesets/finder.ts
  src/rulesets/reader.ts
Labels: bug, documentation

#1058 feat: support async custom functions
  docs/guides/custom-functions.md
  package.json
  src/__tests__/linter.jest.test.ts
  src/functions/schema-path.ts
  src/linter.ts
  src/runner.ts
  src/spectral.ts
  src/types/function.ts
  tsconfig.json
  tsconfig.karma.json
  yarn.lock
Labels: enhancement

#1022 chore: allow running spectral from any directory in Docker
  Dockerfile
Labels: automerge

#1100 chore(schema): expose some extras
  src/functions/schema.ts
Labels: chore

#1105 fix(deps): lock @stoplight/{json,yaml}
  package.json
  yarn.lock
Labels: bug, dependencies

#1106 chore(deps): use locked version of dependencies
  package.json
  yarn.lock
Labels: dependencies

#1113 refactor: drop RuleFunction, Rule and other redundant types/interfaces
  setupTests.ts
  src/__tests__/functions.test.ts
  src/__tests__/spectral.test.ts
  src/functions/alphabetical.ts
  src/functions/casing.ts
  src/functions/enumeration.ts
  src/functions/length.ts
  src/functions/pattern.ts
  src/functions/schema-path.ts
  src/functions/schema.ts
  src/functions/truthy.ts
  src/functions/xor.ts
  src/rulesets/mergers/rules.ts
  src/rulesets/oas/functions/oasOp2xxResponse.ts
  src/rulesets/oas/functions/oasOpFormDataConsumeCheck.ts
  src/rulesets/oas/functions/oasOpIdUnique.ts
  src/rulesets/oas/functions/oasOpParams.ts
  src/rulesets/oas/functions/oasOpSecurityDefined.ts
  src/rulesets/oas/functions/oasPathParam.ts
  src/rulesets/oas/functions/oasTagDefined.ts
  src/rulesets/validation.ts
  src/types/enums.ts
  src/types/rule.ts
  src/types/ruleset.ts
  src/types/spectral.ts
  src/utils/__tests__/pivotExceptions.test.ts
Labels: chore
