Repository stoplightio/spectral, pull requests merged in 2020-01, with the labels that each got.

#865 Updating docs to contain examples for loading custom rulesets in the …
  docs/guides/javascript.md
Labels: automerge

#879 docs: added missing functions: [abc]
  docs/getting-started/openapi.md
  docs/getting-started/rulesets.md
  docs/guides/custom-functions.md
Labels: automerge, documentation

#876 refactor: introduce Document
  docs/guides/javascript.md
  src/__tests__/document.test.ts
  src/__tests__/errorMessages.test.ts
  src/__tests__/linter.test.ts
  src/__tests__/spectral.jest.test.ts
  src/__tests__/spectral.test.ts
  src/cli/services/linter/linter.ts
  src/document.ts
  src/documentInventory.ts
  src/errorMessages.ts
  src/formats/json-schema.ts
  src/formats/openapi.ts
  src/functions/alphabetical.ts
  src/functions/unreferencedReusableObject.ts
  src/index.ts
  src/linter.ts
  src/parsers/json.ts
  src/parsers/types.ts
  src/parsers/yaml.ts
  src/resolved.ts
  src/rulesets/evaluators.ts
  src/rulesets/oas/__tests__/oas2-unused-definition.jest.test.ts
  src/rulesets/oas/__tests__/oas2-unused-definition.karma.test.ts
  src/rulesets/oas/__tests__/oas2-unused-definition.test.ts
  src/rulesets/oas/__tests__/oas3-unused-components-schema.jest.test.ts
  src/rulesets/oas/__tests__/oas3-unused-components-schema.karma.test.ts
  src/rulesets/oas/__tests__/oas3-unused-components-schema.test.ts
  src/rulesets/oas/functions/__tests__/refSiblings.test.ts
  src/rulesets/validation.ts
  src/runner.ts
  src/spectral.ts
  src/types/function.ts
  src/types/spectral.ts
  src/utils/index.ts
  src/utils/isObject.ts
  src/utils/refs.ts
  src/utils/startsWithProtocol.ts
Labels: chore

#900 fix: generate proper paths for rules operating on unresolved documents
  src/__tests__/spectral.jest.test.ts
  src/documentInventory.ts
  src/errorMessages.ts
  src/linter.ts
Labels: bug

#884 feat: Introduce optional enhancers to casing function
  docs/reference/functions.md
  src/functions/__tests__/casing.test.ts
  src/functions/casing.ts
Labels: enhancement

#899 fix: example-value-or-externalValue too broad JsonPath expressions
  src/rulesets/oas/__tests__/example-value-or-externalValue.ts
  src/rulesets/oas/index.json
Labels: bug

#917 fix: schema-path handles falsy values and JSON path expression as field
  src/functions/__tests__/schema-path.test.ts
  src/functions/schema-path.ts
  src/linter.ts
  src/utils/__tests__/getLintTargets.spec.ts
  src/utils/getLintTargets.ts
  src/utils/index.ts
Labels: bug

#914 fix #894: oas3-valid-(content-)schema-example has problem with nullable
  src/functions/__tests__/schema.test.ts
  src/functions/schema-path.ts
  src/functions/schema.ts
  src/rulesets/oas/index.json
Labels: bug

#913 feat: new rule to detect enum value that do not respect specified type
  docs/reference/functions.md
  docs/reference/openapi-rules.md
  src/functions/__tests__/typedEnum.test.ts
  src/functions/index.ts
  src/functions/typedEnum.ts
  src/rulesets/oas/__tests__/typed-enum.ts
  src/rulesets/oas/index.json
  src/types/enums.ts
  src/types/rule.ts
  test-harness/scenarios/enabled-rules-amount.oas3.scenario
  test-harness/scenarios/typed-enum.oas3.scenario
Labels: automerge, enhancement
