Repository stoplightio/spectral, pull requests merged in 2020-07, with the labels that each got.

#1279 chore(deps): bump @stoplight deps
  package.json
  yarn.lock
Labels: dependencies

#1242 feat(ruleset): introduce documentationUrl property
  docs/getting-started/rulesets.md
  src/meta/ruleset.schema.json
  src/rulesets/__tests__/validation.test.ts
  src/rulesets/asyncapi/index.json
  src/rulesets/oas/index.json
  src/rulesets/reader.ts
  src/types/ruleset.ts
Labels: automerge, enhancement

#1288 chore(deps): bump @stoplight/{json-ref-resolver,json}
  package.json
  yarn.lock
Labels: dependencies

#1290 docs: link and formatting updates
  .github/workflows/markdown-links.yml
  README.md
  docs/getting-started/1-concepts.md
  docs/getting-started/2-installation.md
  docs/getting-started/3-rulesets.md
  docs/getting-started/4-openapi.md
  docs/getting-started/5-asyncapi.md
  docs/guides/1-workflows.md
  docs/guides/2-cli.md
  docs/guides/3-javascript.md
  docs/guides/4-custom-rulesets.md
  docs/guides/5-custom-functions.md
  docs/guides/6-exceptions.md
  docs/guides/7-sharing-rulesets.md
  docs/migration-guides/4.0.md
  docs/reference/functions.md
  docs/reference/openapi-rules.md
Labels: documentation
