Repository stoplightio/spectral, pull requests merged in 2020-10, with the labels that each got.

#1368 docs(readme): invalid documentation links
  README.md
Labels: documentation

#1372 docs: move a note on YAML to a separate document
  docs/guides/3-javascript.md
  docs/reference/yaml.md
Labels: documentation

#1354 docs(changelog): release 5.6
  CHANGELOG.md
Labels: documentation

#1360 chore: lint JSON/YAML/Markdown files
  .eslintignore
  .prettierrc.json
  README.md
  docs/getting-started/2-installation.md
  docs/getting-started/3-rulesets.md
  docs/getting-started/4-openapi.md
  docs/guides/2-cli.md
  docs/guides/3-javascript.md
  docs/guides/4-custom-rulesets.md
  docs/guides/5-custom-functions.md
  docs/guides/6-exceptions.md
  docs/guides/7-sharing-rulesets.md
  docs/migration-guides/4.0.md
  docs/migration-guides/5.0.md
  docs/reference/asyncapi-rules.md
  docs/reference/functions.md
  docs/reference/openapi-rules.md
  package.json
  src/meta/rule.schema.json
  src/meta/ruleset.schema.json
  src/rulesets/asyncapi/index.json
  src/rulesets/asyncapi/schemas/schema.asyncapi2.json
  src/rulesets/oas/index.json
  src/rulesets/oas/schemas/schema.oas3.json
Labels: chore

#1375 fix(cli): JUnit formatter respects fail-severity
  docs/guides/2-cli.md
  package.json
  src/cli/commands/__tests__/lint.test.ts
  src/cli/commands/lint.ts
  src/cli/formatters/__tests__/__fixtures__/mixed-errors-with-different-paths.json
  src/cli/formatters/__tests__/__fixtures__/mixed-errors.json
  src/cli/formatters/__tests__/__fixtures__/oas3-schema-errors.json
  src/cli/formatters/__tests__/html.test.ts
  src/cli/formatters/__tests__/json.test.ts
  src/cli/formatters/__tests__/junit.test.ts
  src/cli/formatters/__tests__/stylish.test.ts
  src/cli/formatters/__tests__/teamcity.test.ts
  src/cli/formatters/__tests__/text.test.ts
  src/cli/formatters/html/html-template-message.html
  src/cli/formatters/html/html-template-page.html
  src/cli/formatters/html/html-template-result.html
  src/cli/formatters/html/index.ts
  src/cli/formatters/index.ts
  src/cli/formatters/json.ts
  src/cli/formatters/junit.ts
  src/cli/formatters/stylish.ts
  src/cli/formatters/teamcity.ts
  src/cli/formatters/text.ts
  src/cli/formatters/types.ts
  src/cli/formatters/utils/getColorForSeverity.ts
  src/cli/formatters/utils/getHighestSeverity.ts
  src/cli/formatters/utils/getSeverityName.ts
  src/cli/formatters/utils/getSummary.ts
  src/cli/formatters/utils/groupBySeverity.ts
  src/cli/formatters/utils/groupBySource.ts
  src/cli/formatters/utils/index.ts
  src/cli/formatters/utils/pluralize.ts
  src/cli/formatters/utils/xmlEscape.ts
  src/cli/services/__tests__/output.test.ts
  src/cli/services/output.ts
  src/formatters/types.ts
  test-harness/scenarios/help-no-document.scenario
Labels: bug

#1377 fix(schema): handle non-string enum values
  package.json
  src/functions/__tests__/schema.test.ts
  src/rulesets/asyncapi/__tests__/asyncapi-headers-schema-type-object.ts
  test-harness/scenarios/examples.oas2.scenario
  test-harness/scenarios/examples.oas3.scenario
  test-harness/scenarios/external-schemas-ruleset.scenario
  yarn.lock
Labels: bug

#1376 fix(typed-enum): respect nullable in case of OAS3 document
  src/rulesets/oas/__tests__/typed-enum.ts
  src/rulesets/oas/functions/__tests__/typedEnum.test.ts
  src/rulesets/oas/functions/typedEnum.ts
Labels: bug

#1371 feat(cli): introduce --fail-on-unmatched-globs flag
  docs/guides/2-cli.md
  package.json
  src/cli/commands/__tests__/lint.test.ts
  src/cli/commands/lint.ts
  src/cli/services/linter/linter.ts
  src/types/config.ts
  test-harness/scenarios/fail-on-unmatched-glob-patterns.scenario
  test-harness/scenarios/help-no-document.scenario
  yarn.lock
Labels: enhancement

#1370 docs(custom-functions): update otherValues & add info about core fns
  docs/guides/5-custom-functions.md
Labels: documentation

#1379 fix(oas-valid-example): ignore externalValue
  src/rulesets/oas/__tests__/oas3-valid-media-example.test.ts
  src/rulesets/oas/functions/oasExample.ts
Labels: bug

#1369 feat(ruleset): allow documentationUrl to be specified for each rule
  docs/guides/4-custom-rulesets.md
  src/meta/rule.schema.json
  src/rulesets/__tests__/__fixtures__/documentation-url-ruleset.json
  src/rulesets/__tests__/reader.jest.test.ts
  src/rulesets/__tests__/validation.test.ts
  src/rulesets/reader.ts
  src/types/rule.ts
  src/types/ruleset.ts
Labels: enhancement

#1378 feat(schema): supports x-nullable for OAS2
  package.json
  patches/ajv+6.12.5.patch
  src/functions/__tests__/schema.test.ts
  src/functions/schema.ts
  src/rulesets/oas/__tests__/typed-enum.ts
  src/rulesets/oas/functions/typedEnum.ts
  yarn.lock
Labels: bug

#1351 style: address a few ESLint warnings
  .eslintrc
  src/assets.ts
  src/cli/commands/lint.ts
  src/cli/formatters/html/index.ts
  src/cli/formatters/stylish.ts
  src/cli/formatters/teamcity.ts
  src/cli/formatters/text.ts
  src/cli/formatters/utils/getColorForSeverity.ts
  src/cli/formatters/utils/getHighestSeverity.ts
  src/cli/formatters/utils/getSeverityName.ts
  src/cli/formatters/utils/getSummary.ts
  src/cli/formatters/utils/groupBySeverity.ts
  src/cli/formatters/utils/groupBySource.ts
  src/cli/formatters/utils/xmlEscape.ts
  src/cli/services/linter/linter.ts
  src/cli/services/linter/utils/getResolver.ts
  src/errorMessages.ts
  src/formats/asyncapi.ts
  src/formats/json-schema.ts
  src/formats/openapi.ts
  src/functions/alphabetical.ts
  src/parsers/json.ts
  src/parsers/yaml.ts
  src/request.ts
  src/rule.ts
  src/rulesets/mergers/rules.ts
  src/runner/lintNode.ts
  src/runner/runner.ts
  src/runner/runtime.ts
  src/runner/utils/getLintTargets.ts
  src/runner/utils/pivotExceptions.ts
  src/types/rule.ts
  src/utils/__tests__/sortResults.test.ts
  src/utils/empty.ts
  src/utils/generateDocumentWideResult.ts
  src/utils/hasIntersectingElement.ts
  src/utils/prepareResults.ts
  src/utils/printPath.ts
  src/utils/refs.ts
  src/utils/sortResults.ts
  src/utils/startsWithProtocol.ts
  test-harness/index.ts
Labels: chore

#1361 feat(ruleset): introduce parser options
  docs/guides/4-custom-rulesets.md
  src/__tests__/linter.test.ts
  src/consts.ts
  src/document.ts
  src/errorMessages.ts
  src/meta/rule.schema.json
  src/meta/ruleset.schema.json
  src/meta/shared.json
  src/rulesets/__tests__/__fixtures__/parser-options-ruleset.json
  src/rulesets/__tests__/reader.jest.test.ts
  src/rulesets/__tests__/validation.test.ts
  src/rulesets/reader.ts
  src/rulesets/validation.ts
  src/spectral.ts
  src/types/ruleset.ts
  test-harness/scenarios/severity/fail-on-error.oas3.scenario
Labels: enhancement
