Repository stoplightio/spectral, pull requests merged in 2020-12, with the labels that each got.

#1411 fix: user-friendly error for empty rulesets
  src/rulesets/__tests__/reader.jest.test.ts
  src/rulesets/reader.ts
Labels: bug

#1420 docs(changelog): release 5.7.2
  CHANGELOG.md
Labels: documentation

#1421 chore: lint CHANGELOG
  CHANGELOG.md
  package.json
  yarn.lock
Labels: chore

#1423 feat(ruleset): optional source for exceptions
  docs/guides/6-exceptions.md
  src/__tests__/__fixtures__/exceptions.remote.oas3.yaml
  src/__tests__/__fixtures__/rulesets/exceptions-resolving.json
  src/__tests__/linter.jest.test.ts
  src/rulesets/mergers/__tests__/exceptions.test.ts
  src/rulesets/mergers/exceptions.ts
  src/runner/lintNode.ts
  src/runner/runner.ts
  src/runner/utils/__tests__/pivotExceptions.test.ts
  src/runner/utils/isAKnownException.ts
  src/runner/utils/pivotExceptions.ts
Labels: enhancement

#1424 docs(readme): tune-up
  README.md
  docs/img/readme-header.svg
Labels: documentation

#1418 fix(oas): validate falsy examples
  src/rulesets/oas/__tests__/oas2-valid-schema-example.ts
  src/rulesets/oas/__tests__/oas3-valid-media-example.test.ts
  src/rulesets/oas/__tests__/oas3-valid-schema-example.ts
  src/rulesets/oas/index.json
Labels: automerge, bug

#1417 fix(oas): path-params rule flags parameter override definitions as duplicate
  src/rulesets/oas/functions/__tests__/oasPathParam.test.ts
  src/rulesets/oas/functions/oasPathParam.ts
Labels: automerge, bug

#1427 fix(ruleset): Allow single trailing slash for oas3 server url
  src/rulesets/oas/__tests__/oas3-server-trailing-slash.ts
  src/rulesets/oas/index.json
Labels: bug

#1428 fix(oas): oas3-examples-value-or-externalValue is too broad
  src/rulesets/oas/__tests__/oas3-examples-value-or-externalValue.ts
  src/rulesets/oas/index.json
Labels: bug

#1306 chore: make readfile/readParsable unaware of file descriptors
  src/cli/services/linter/linter.ts
  src/cli/services/linter/utils/__tests__/__fixtures__/simple
  src/cli/services/linter/utils/__tests__/readFileDescriptor.jest.test.ts
  src/cli/services/linter/utils/__tests__/segregateEntriesPerKind.test.ts
  src/cli/services/linter/utils/index.ts
  src/cli/services/linter/utils/listFiles.ts
  src/cli/services/linter/utils/readFileDescriptor.ts
  src/cli/services/linter/utils/segregateEntriesPerKind.ts
  src/fs/__tests__/reader.jest.test.ts
  src/fs/reader.ts
Labels: chore

#1429 feat(oas): validate 'default' in schemas
  src/rulesets/oas/__tests__/oas2-valid-schema-example.ts
  src/rulesets/oas/__tests__/oas3-valid-schema-example.ts
  src/rulesets/oas/functions/oasExample.ts
  src/rulesets/oas/index.json
Labels: enhancement
