Repository stoplightio/spectral, pull requests merged in 2020-06, with the labels that each got.

#1189 chore: generate more efficient assets
  package.json
  rollup.config.js
  scripts/generate-assets.ts
  src/rulesets/asyncapi/functions/asyncApi2PayloadValidation.ts
  src/rulesets/oas/functions/oasOp2xxResponse.ts
  src/rulesets/oas/functions/oasOpFormDataConsumeCheck.ts
  src/rulesets/oas/functions/oasOpIdUnique.ts
  src/rulesets/oas/functions/oasOpParams.ts
  src/rulesets/oas/functions/oasOpSecurityDefined.ts
  src/rulesets/oas/functions/oasPathParam.ts
  src/rulesets/oas/functions/oasTagDefined.ts
  src/rulesets/oas/functions/refSiblings.ts
  src/rulesets/oas/functions/typedEnum.ts
  yarn.lock
Labels: chore

#1192 chore(deps): set monthly schedule
  .dependabot/config.yml
Labels: chore

#1207 fix(deps): bump @stoplight/json-ref-resolver to 3.0.9
  package.json
  yarn.lock
Labels: automerge, dependencies

#1215 chore: expose Spectral version
  scripts/inline-version.js
  src/consts.ts
  src/index.ts
  src/rulesets/finder.ts
Labels: chore

#1214 fix: do not attempt to resolve primitive values
  src/__tests__/linter.test.ts
  src/documentInventory.ts
  src/functions/unreferencedReusableObject.ts
  src/runner/runner.ts
Labels: bug

#1222 chore(readme): apache license 2.0 is used
  README.md
Labels: chore

#1227 fix: check against valid operations before checking parameters exist.
  docs/reference/openapi-rules.md
  src/rulesets/oas/functions/__tests__/oasPathParam.test.ts
  src/rulesets/oas/functions/oasPathParam.ts
Labels: bug

#1233 chore: export KNOWN_RULESETS
  scripts/generate-assets.ts
  src/cli/services/linter/utils/getRuleset.ts
  src/formats/consts.ts
Labels: chore

#1236 feat: use @stoplight/better-ajv-errors
  package.json
  src/cli/services/__tests__/linter.test.ts
  src/functions/__tests__/schema-path.test.ts
  src/functions/__tests__/schema.test.ts
  src/functions/schema.ts
  src/rulesets/asyncapi/__tests__/asyncapi-headers-schema-type-object.ts
  src/rulesets/asyncapi/__tests__/asyncapi-payload-default.ts
  src/rulesets/asyncapi/__tests__/asyncapi-payload-examples.ts
  src/rulesets/asyncapi/functions/__tests__/asyncApi2PayloadValidation.test.ts
  src/rulesets/oas/__tests__/oas2-valid-definition-example.ts
  src/rulesets/oas/__tests__/oas2-valid-parameter-example.ts
  src/rulesets/oas/__tests__/oas3-valid-oas-parameter-example.ts
  src/rulesets/oas/__tests__/oas3-valid-parameter-schema-example.ts
  src/rulesets/oas/__tests__/oas3-valid-schema-example.ts
  src/rulesets/oas/__tests__/templates/_oas-example.ts
  src/rulesets/oas/__tests__/templates/_schema-example.ts
  test-harness/scenarios/external-schemas-ruleset.scenario
  test-harness/scenarios/oas3-schema.scenario
  yarn.lock
Labels: automerge, tech-debt

#1239 test(reader): try to reduce flakiness under Windows
  src/fs/__tests__/reader.jest.test.ts
Labels: chore

#1247 chore(dependabot): use version 2
  .dependabot/config.yml
  .github/dependabot.yml
Labels: chore

#1240 fix(oas): operation-paramaters outputs better messages
  src/rulesets/oas/functions/__tests__/oasOpParams.test.ts
  src/rulesets/oas/functions/oasOpParams.ts
  src/rulesets/oas/index.json
Labels: bug

#1253 chore(deps): bump @stoplight/{json,yaml}
  karma.conf.ts
  package.json
  tslint.json
  yarn.lock
Labels: dependencies

#1256 fix: casing fn handles leading char
  src/functions/__tests__/casing.test.ts
  src/functions/casing.ts
Labels: bug
