Repository stoplightio/spectral, pull requests merged in 2020-03, with the labels that each got.

#988 docs(rulesets): reorganize chapters
  docs/getting-started/rulesets.md
Labels: documentation

#1009 fix(yaml): change severity of YAMLIncomaptibleValue diagnostics
  package.json
  src/__tests__/linter.test.ts
  test-harness/scenarios/severity/fail-on-error.oas3.scenario
  yarn.lock
Labels: bug

#1011 feat(ruleset): allow require calls in Node.JS
  docs/guides/custom-functions.md
  src/__tests__/__fixtures__/custom-functions-oas-ruleset.json
  src/__tests__/__fixtures__/functions/deepHasIn.js
  src/__tests__/linter.jest.test.ts
  src/rulesets/__tests__/__fixtures__/foo.js
  src/rulesets/__tests__/evaluators.jest.test.ts
  src/rulesets/__tests__/evaluators.karma.test.ts
  src/rulesets/__tests__/evaluators.test.ts
  src/rulesets/__tests__/reader.jest.test.ts
  src/rulesets/evaluators.ts
  src/rulesets/mergers/__tests__/functions.jest.test.ts
  src/rulesets/mergers/functions.ts
  src/rulesets/reader.ts
  src/spectral.ts
  src/types/ruleset.ts
Labels: enhancement

#1007 chore: add stoplight config file
  .stoplight.json
Labels: chore

#1008 fix(alphabetical): account for lost proxies
  package.json
  rollup.config.js
  src/document.ts
  src/functions/__tests__/alphabetical.test.ts
  src/functions/__tests__/casing.test.ts
  src/functions/__tests__/typedEnum.test.ts
  src/functions/alphabetical.ts
  src/functions/unreferencedReusableObject.ts
  src/linter.ts
  src/parsers/json.ts
  src/parsers/types.ts
  src/parsers/yaml.ts
  src/types/function.ts
  yarn.lock
Labels: bug

#1017 docs(changelog): 5.2 release
  CHANGELOG.md
Labels: documentation

#1025 test(jest): nanoid mock
  __mocks__/nanoid/non-secure.ts
  package.json
  src/rulesets/__tests__/reader.jest.test.ts
  src/rulesets/mergers/__tests__/functions.jest.test.ts
  yarn.lock
Labels: chore

#1029 fix(rulesets): require node_module
  src/rulesets/evaluators.ts
  test-harness/index.ts
  test-harness/scenarios/require-module.scenario
Labels: bug

#925 feat: expose available functions to custom functions
  docs/guides/custom-functions.md
  src/__tests__/__fixtures__/custom-functions-oas-ruleset.json
  src/__tests__/__fixtures__/functions/validateBar.js
  src/__tests__/linter.jest.test.ts
  src/functions/index.ts
  src/rulesets/__tests__/evaluators.test.ts
  src/rulesets/evaluators.ts
  src/spectral.ts
  src/types/function.ts
Labels: enhancement

#1040 fix: set proper document source if legacy parsed result is given
  src/__tests__/linter.test.ts
  src/document.ts
  src/spectral.ts
Labels: bug

#1036 chore: adding Treeware Tree badge
  README.md
Labels: chore
