Repository stoplightio/spectral, pull requests merged in 2021-12, with the labels that each got.

#1987 chore(repo): remove Dependabot
  .github/dependabot.yml
Labels: chore

#1993 feat(core): expose x-internal to annotate internal opts
  packages/core/src/ruleset/rulesetFunction.ts
  packages/core/src/ruleset/validation.ts
Labels: enhancement

#1994 build(repo): on-demand releases & improve caching
  .circleci/config.yml
  .yarn/install-state.gz
  package.json
  yarn.lock
Labels: chore

#1985 fix(ruleset-bundler): improve package import heuristics
  packages/ruleset-bundler/src/index.ts
  packages/ruleset-bundler/src/plugins/skypack.ts
  packages/ruleset-bundler/src/utils/__tests__/isPackageImport.spec.ts
  packages/ruleset-bundler/src/utils/isPackageImport.ts
  packages/ruleset-bundler/src/utils/isValidPackageName.ts
Labels: t/bug

#1988 feat(ruleset-bundler): add ruleset loader
  .yarn/install-state.gz
  packages/ruleset-bundler/README.md
  packages/ruleset-bundler/package.json
  packages/ruleset-bundler/src/__tests__/index.test.ts
  packages/ruleset-bundler/src/index.ts
  packages/ruleset-bundler/src/loader/__tests__/__fixtures__/.spectral/helpers/index.js
  packages/ruleset-bundler/src/loader/__tests__/__fixtures__/.spectral/helpers/is-odd.js
  packages/ruleset-bundler/src/loader/__tests__/__fixtures__/.spectral/lower-case.js
  packages/ruleset-bundler/src/loader/__tests__/__fixtures__/.spectral/my-fn.js
  packages/ruleset-bundler/src/loader/__tests__/__fixtures__/.spectral/upper-case.js
  packages/ruleset-bundler/src/loader/__tests__/__fixtures__/spectral.js
  packages/ruleset-bundler/src/loader/__tests__/__fixtures__/spectral.json
  packages/ruleset-bundler/src/loader/__tests__/browser.test.ts
  packages/ruleset-bundler/src/loader/__tests__/node.jest.test.ts
  packages/ruleset-bundler/src/loader/browser.ts
  packages/ruleset-bundler/src/loader/common/bundle.ts
  packages/ruleset-bundler/src/loader/common/utils.ts
  packages/ruleset-bundler/src/loader/node.ts
  packages/ruleset-bundler/src/loader/types.ts
  packages/ruleset-bundler/tsconfig.build.json
  packages/ruleset-migrator/README.md
  test-utils/node/index.ts
  yarn.lock
Labels: enhancement

#1986 perf(rulesets): simplify JSONPath expressions
  .yarn/install-state.gz
  packages/rulesets/src/asyncapi/index.ts
  packages/rulesets/src/oas/index.ts
Labels: chore

#2012 fix(core): update nimma & json-schema
  .yarn/install-state.gz
  package.json
  packages/core/package.json
  packages/core/src/runner/runner.ts
  packages/functions/src/__tests__/__helpers__/tester.ts
  yarn.lock
Labels: dependencies

#2004 docs(repo): fix example for operation-id-kebab-case
  docs/guides/5-custom-functions.md
Labels: documentation
