Repository stoplightio/spectral, pull requests merged in 2021-08, with the labels that each got.

#1764 feat(ruleset-migrator): overridable fetch
  packages/ruleset-migrator/package.json
  packages/ruleset-migrator/src/__tests__/ruleset.test.ts
  packages/ruleset-migrator/src/index.ts
  packages/ruleset-migrator/src/transformers/extends.ts
  packages/ruleset-migrator/src/types.ts
Labels: enhancement

#1766 docs(repo): tweak JS API usage
  README.md
  docs/getting-started/2-installation.md
  docs/guides/1-workflows.md
  docs/guides/3-javascript.md
  docs/migration-guides/6.0.md
Labels: documentation

#1758 feat(ruleset-migrator): assert safe & unique identifiers
  packages/ruleset-migrator/package.json
  packages/ruleset-migrator/src/__tests__/__fixtures__/extends-variant-6/output.cjs
  packages/ruleset-migrator/src/__tests__/__fixtures__/extends-variant-6/output.mjs
  packages/ruleset-migrator/src/__tests__/__fixtures__/extends-variant-7/assets/ruleset-2.yaml
  packages/ruleset-migrator/src/__tests__/__fixtures__/extends-variant-7/assets/ruleset-3.yaml
  packages/ruleset-migrator/src/__tests__/__fixtures__/extends-variant-7/assets/ruleset.yaml
  packages/ruleset-migrator/src/__tests__/__fixtures__/extends-variant-7/output.cjs
  packages/ruleset-migrator/src/__tests__/__fixtures__/extends-variant-7/output.mjs
  packages/ruleset-migrator/src/__tests__/__fixtures__/extends-variant-7/ruleset.yaml
  packages/ruleset-migrator/src/__tests__/__fixtures__/functions-variant-3/output.cjs
  packages/ruleset-migrator/src/__tests__/__fixtures__/functions-variant-3/output.mjs
  packages/ruleset-migrator/src/__tests__/__fixtures__/functions-variant-3/ruleset.yaml
  packages/ruleset-migrator/src/__tests__/__fixtures__/functions-variant-4/output.cjs
  packages/ruleset-migrator/src/__tests__/__fixtures__/functions-variant-4/output.mjs
  packages/ruleset-migrator/src/__tests__/__fixtures__/functions-variant-4/ruleset.yaml
  packages/ruleset-migrator/src/__tests__/__fixtures__/rules-variant-1/output.cjs
  packages/ruleset-migrator/src/__tests__/__fixtures__/rules-variant-1/output.mjs
  packages/ruleset-migrator/src/__tests__/__fixtures__/rules-variant-2/output.cjs
  packages/ruleset-migrator/src/__tests__/__fixtures__/rules-variant-2/output.mjs
  packages/ruleset-migrator/src/__tests__/__fixtures__/rules-variant-2/ruleset.yaml
  packages/ruleset-migrator/src/index.ts
  packages/ruleset-migrator/src/transformers/extends.ts
  packages/ruleset-migrator/src/transformers/functions.ts
  packages/ruleset-migrator/src/transformers/rules.ts
  packages/ruleset-migrator/src/tree/index.ts
  packages/ruleset-migrator/src/tree/scope.ts
  packages/ruleset-migrator/src/types.ts
  packages/ruleset-migrator/tsconfig.build.json
  packages/ruleset-migrator/types/reserved.d.ts
  yarn.lock
Labels: enhancement

#1771 fix(functions): schema should respect "auto" dialect
  packages/functions/src/__tests__/schema.test.ts
  packages/functions/src/schema/index.ts
Labels: t/bug

#1777 feat(core): expose underlying schemas in RulesetFunctionWithValidator
  packages/core/package.json
  packages/core/src/ruleset/rulesetFunction.ts
  packages/core/src/types/function.ts
Labels: enhancement

#1735 build(repo): cached-dependencies on Windows
  .circleci/config.yml
Labels: chore

#1772 fix(ruleset-migrator): handle path-only exceptions correctly
  packages/ruleset-migrator/src/__tests__/__fixtures__/exceptions-variant-2/output.cjs
  packages/ruleset-migrator/src/__tests__/__fixtures__/exceptions-variant-2/output.mjs
  packages/ruleset-migrator/src/__tests__/__fixtures__/exceptions-variant-2/ruleset.yaml
  packages/ruleset-migrator/src/transformers/except.ts
Labels: t/bug

#1774 fix(rulesets): oasSchema not using correct dialect for OAS 3.1
  packages/rulesets/package.json
  packages/rulesets/src/oas/functions/__tests__/oasSchema.test.ts
  packages/rulesets/src/oas/functions/oasSchema.ts
Labels: t/bug

#1784 fix(ruleset-migrator): occasionally broken length function import
  packages/ruleset-migrator/src/__tests__/__fixtures__/rules-variant-3/output.cjs
  packages/ruleset-migrator/src/__tests__/__fixtures__/rules-variant-3/output.mjs
  packages/ruleset-migrator/src/__tests__/__fixtures__/rules-variant-3/ruleset.yaml
  packages/ruleset-migrator/src/tree/index.ts
Labels: t/bug

#1781 fix(rulesets): oasExample not handling boolean-ish required
  packages/rulesets/src/oas/__tests__/oas2-valid-schema-example.test.ts
  packages/rulesets/src/oas/functions/oasExample.ts
Labels: t/bug

#1793 fix(rulesets): operation-success-response rule does not respect 2XX and 3XX
  packages/rulesets/src/oas/__tests__/operation-success-response.test.ts
  packages/rulesets/src/oas/functions/oasOpSuccessResponse.ts
Labels: t/bug

#1787 fix(functions): schema fn should allow redundant escapes
  packages/functions/src/__tests__/schema.test.ts
  packages/functions/src/schema/ajv.ts
Labels: t/bug

#1801 feat(functions): output Ajv runtime exceptions
  packages/functions/src/__tests__/schema.test.ts
  packages/functions/src/schema/index.ts
Labels: enhancement
