Repository stoplightio/spectral, pull requests merged in 2021-01, with the labels that each got.

#1444 build(gh): remove automerge workflow
  .github/workflows/automerge.yml
Labels: chore

#1443 docs(changelog): release 5.8
  CHANGELOG.md
Labels: documentation

#1430 fix(oas): improve invalid paramaters detection
  package.json
  src/cli/services/__tests__/linter.test.ts
  test-harness/scenarios/oas3-schema.scenario
  yarn.lock
Labels: bug

#1464 docs: explain about JSON Path Plus
  docs/guides/4-custom-rulesets.md
Labels: documentation

#1467 test: reorganize rulesets tests
  src/__tests__/__fixtures__/rulesets/disabled.json
  src/__tests__/__fixtures__/studio-default-fixture-oas3.json
  src/__tests__/linter.jest.test.ts
  src/__tests__/linter.test.ts
  src/rulesets/__tests__/__fixtures__/custom-oas-ruleset.json
  src/rulesets/__tests__/__fixtures__/customFunctionsRuleset/customFunctions/bar.js
  src/rulesets/__tests__/__fixtures__/customFunctionsRuleset/customFunctions/truthy.js
  src/rulesets/__tests__/__fixtures__/customFunctionsRuleset/ruleset.json
  src/rulesets/__tests__/__fixtures__/enable-all-ruleset.json
  src/rulesets/__tests__/__fixtures__/exceptions/invalid.yaml
  src/rulesets/__tests__/__fixtures__/exceptions/simple.yaml
  src/rulesets/__tests__/__fixtures__/extends-disabled-oas-ruleset.yaml
  src/rulesets/__tests__/__fixtures__/extends-oas-with-override-ruleset.json
  src/rulesets/__tests__/__fixtures__/extends-only-ruleset.json
  src/rulesets/__tests__/__fixtures__/extends-relative-ruleset.json
  src/rulesets/__tests__/__fixtures__/formats/oas2.json
  src/rulesets/__tests__/__fixtures__/formats/oas3.json
  src/rulesets/__tests__/__fixtures__/formats/ruleset.json
  src/rulesets/__tests__/__fixtures__/github-issue-447-fixture.yaml
  src/rulesets/__tests__/__fixtures__/my-open-api-ruleset.json
  src/rulesets/__tests__/__fixtures__/npm/plain.json
  src/rulesets/__tests__/__fixtures__/npm/versioned.json
  src/rulesets/__tests__/__fixtures__/severity/all.json
  src/rulesets/__tests__/__fixtures__/severity/implicit.json
  src/rulesets/__tests__/__fixtures__/severity/off.json
  src/rulesets/__tests__/__fixtures__/severity/recommended.json
  src/rulesets/__tests__/__fixtures__/severity/shared.json
  src/rulesets/__tests__/__fixtures__/simple-disable-ruleset.yaml
  src/rulesets/__tests__/__fixtures__/valid-flat-ruleset-2.json
  src/rulesets/__tests__/__fixtures__/valid-flat-ruleset.json
  src/rulesets/__tests__/__fixtures__/valid-require-info-ruleset.yaml
  src/rulesets/__tests__/reader.jest.test.ts
  src/rulesets/oas/__tests__/__fixtures__/unusedShared/unusedComponentsSchema.definition.json
  src/rulesets/oas/__tests__/__fixtures__/unusedShared/unusedComponentsSchema.indirect.1.json
  src/rulesets/oas/__tests__/__fixtures__/unusedShared/unusedComponentsSchema.indirect.2.json
  src/rulesets/oas/__tests__/__fixtures__/unusedShared/unusedComponentsSchema.remoteLocal.json
  src/rulesets/oas/__tests__/__fixtures__/unusedShared/unusedDefinition.definition.json
  src/rulesets/oas/__tests__/__fixtures__/unusedShared/unusedDefinition.indirect.1.json
  src/rulesets/oas/__tests__/__fixtures__/unusedShared/unusedDefinition.indirect.2.json
  src/rulesets/oas/__tests__/__fixtures__/unusedShared/unusedDefinition.remoteLocal.json
  src/rulesets/oas/__tests__/no-$ref-siblings.ts
  src/rulesets/oas/__tests__/oas2-parameter-description.ts
  src/rulesets/oas/__tests__/oas2-unused-definition.jest.test.ts
  src/rulesets/oas/__tests__/oas3-parameter-description.ts
  src/rulesets/oas/__tests__/oas3-unused-components-schema.jest.test.ts
  src/rulesets/oas/__tests__/shared/_parameter-description.ts
Labels: chore

#1458 fix: address Webpack warning
  src/rulesets/evaluators.ts
Labels: bug

#1473 test(asyncapi): align tests with oas
  azure-pipelines.yml
  jest.config.js
  setupTests.ts
  src/__tests__/spectral.test.ts
  src/rulesets/asyncapi/__tests__/__helpers__/createWithRules.ts
  src/rulesets/asyncapi/__tests__/asyncapi-channel-no-empty-parameter.ts
  src/rulesets/asyncapi/__tests__/asyncapi-channel-no-query-nor-fragment.ts
  src/rulesets/asyncapi/__tests__/asyncapi-channel-no-trailing-slash.ts
  src/rulesets/asyncapi/__tests__/asyncapi-headers-schema-type-object.ts
  src/rulesets/asyncapi/__tests__/asyncapi-info-contact-properties.ts
  src/rulesets/asyncapi/__tests__/asyncapi-info-contact.ts
  src/rulesets/asyncapi/__tests__/asyncapi-info-description.ts
  src/rulesets/asyncapi/__tests__/asyncapi-info-license-url.ts
  src/rulesets/asyncapi/__tests__/asyncapi-info-license.ts
  src/rulesets/asyncapi/__tests__/asyncapi-operation-description.ts
  src/rulesets/asyncapi/__tests__/asyncapi-operation-operationId.ts
  src/rulesets/asyncapi/__tests__/asyncapi-parameter-description.ts
  src/rulesets/asyncapi/__tests__/asyncapi-payload-default.ts
  src/rulesets/asyncapi/__tests__/asyncapi-payload-examples.ts
  src/rulesets/asyncapi/__tests__/asyncapi-payload-unsupported-schemaFormat.ts
  src/rulesets/asyncapi/__tests__/asyncapi-payload.ts
  src/rulesets/asyncapi/__tests__/asyncapi-schema-default.ts
  src/rulesets/asyncapi/__tests__/asyncapi-schema-examples.ts
  src/rulesets/asyncapi/__tests__/asyncapi-schema.ts
  src/rulesets/asyncapi/__tests__/asyncapi-server-no-empty-variable.ts
  src/rulesets/asyncapi/__tests__/asyncapi-server-no-trailing-slash.ts
  src/rulesets/asyncapi/__tests__/asyncapi-server-not-example-com.ts
  src/rulesets/asyncapi/__tests__/asyncapi-servers.ts
  src/rulesets/asyncapi/__tests__/asyncapi-tag-description.ts
  src/rulesets/asyncapi/__tests__/asyncapi-tags-alphabetical.ts
  src/rulesets/asyncapi/__tests__/asyncapi-tags.ts
  src/rulesets/asyncapi/__tests__/asyncapi-unused-components-schema.ts
  src/rulesets/mergers/__tests__/exceptions.test.ts
  src/runner/utils/__tests__/pivotExceptions.test.ts
Labels: chore

#1472 test(oas): reduce the amount of boilerplate
  src/rulesets/oas/__tests__/__helpers__/createWithRules.ts
  src/rulesets/oas/__tests__/contact-properties.ts
  src/rulesets/oas/__tests__/info-contact.ts
  src/rulesets/oas/__tests__/info-description.ts
  src/rulesets/oas/__tests__/info-license.ts
  src/rulesets/oas/__tests__/license-url.ts
  src/rulesets/oas/__tests__/no-$ref-siblings.ts
  src/rulesets/oas/__tests__/no-eval-in-markdown.ts
  src/rulesets/oas/__tests__/no-script-tags-in-markdown.ts
  src/rulesets/oas/__tests__/oas2-anyOf.ts
  src/rulesets/oas/__tests__/oas2-api-host.ts
  src/rulesets/oas/__tests__/oas2-api-schemes.ts
  src/rulesets/oas/__tests__/oas2-host-not-example.ts
  src/rulesets/oas/__tests__/oas2-host-trailing-slash.ts
  src/rulesets/oas/__tests__/oas2-oneOf.ts
  src/rulesets/oas/__tests__/oas2-schema.ts
  src/rulesets/oas/__tests__/oas2-unused-definition.jest.test.ts
  src/rulesets/oas/__tests__/oas2-unused-definition.karma.test.ts
  src/rulesets/oas/__tests__/oas2-unused-definition.test.ts
  src/rulesets/oas/__tests__/oas2-valid-media-example.ts
  src/rulesets/oas/__tests__/oas2-valid-schema-example.ts
  src/rulesets/oas/__tests__/oas3-api-servers.ts
  src/rulesets/oas/__tests__/oas3-examples-value-or-externalValue.ts
  src/rulesets/oas/__tests__/oas3-server-not-example.ts
  src/rulesets/oas/__tests__/oas3-server-trailing-slash.ts
  src/rulesets/oas/__tests__/oas3-unused-components-schema.jest.test.ts
  src/rulesets/oas/__tests__/oas3-unused-components-schema.karma.test.ts
  src/rulesets/oas/__tests__/oas3-unused-components-schema.test.ts
  src/rulesets/oas/__tests__/oas3-valid-media-example.test.ts
  src/rulesets/oas/__tests__/oas3-valid-schema-example.ts
  src/rulesets/oas/__tests__/openapi-tags-alphabetical.ts
  src/rulesets/oas/__tests__/openapi-tags.ts
  src/rulesets/oas/__tests__/operation-description.ts
  src/rulesets/oas/__tests__/operation-operationId-valid-in-url.ts
  src/rulesets/oas/__tests__/operation-operationId.ts
  src/rulesets/oas/__tests__/operation-singular-tag.ts
  src/rulesets/oas/__tests__/operation-success-response.ts
  src/rulesets/oas/__tests__/operation-tags.ts
  src/rulesets/oas/__tests__/path-declarations-must-exist.ts
  src/rulesets/oas/__tests__/path-keys-no-trailing-slash.ts
  src/rulesets/oas/__tests__/path-not-include-query.ts
  src/rulesets/oas/__tests__/tag-description.ts
  src/rulesets/oas/__tests__/typed-enum.ts
  src/rulesets/oas/__tests__/valid-example.test.ts
Labels: chore

#1468 docs: explain Recommended/All
  docs/guides/4-custom-rulesets.md
Labels: documentation

#1465 fix: nested extends broken in rulesets
  src/rule.ts
  src/ruleset/__tests__/__fixtures__/severity/off-proxy.json
  src/ruleset/__tests__/reader.jest.test.ts
  src/ruleset/__tests__/severity.test.ts
  src/ruleset/mergers/__tests__/rules.test.ts
  src/ruleset/mergers/rules.ts
  src/ruleset/readRuleset.ts
  src/ruleset/severity.ts
  src/runner/lintNode.ts
  src/types/rule.ts
  src/types/spectral.ts
Labels: bug

#1433 feat: rework error filtering to preserve sibling additionalProperties errors
  src/__tests__/__fixtures__/invalid-status-codes.oas3.json
  src/__tests__/generate-assets.jest.test.ts
  src/__tests__/linter.test.ts
  src/__tests__/spectral.jest.test.ts
  src/cli/services/__tests__/linter.test.ts
  src/functions/schema.ts
  src/rulesets/oas/functions/__tests__/oasDocumentSchema.test.ts
  src/rulesets/oas/functions/oasDocumentSchema.ts
  test-harness/scenarios/oas3-schema.scenario
  test-harness/scenarios/results-format-junit.oas3.scenario
Labels: enhancement

#1440 feat(oas): add oas3-unused-component rule which detects all orphaned components
  docs/reference/openapi-rules.md
  src/__tests__/linter.test.ts
  src/cli/services/__tests__/linter.test.ts
  src/rulesets/__tests__/__fixtures__/unusedComponent.json
  src/rulesets/__tests__/__fixtures__/unusedComponent.negative.json
  src/rulesets/oas/__tests__/oas3-unused-component.jest.test.ts
  src/rulesets/oas/__tests__/oas3-unused-component.karma.test.ts
  src/rulesets/oas/__tests__/oas3-unused-component.test.ts
  src/rulesets/oas/__tests__/oas3-unused-components-schema.test.ts
  src/rulesets/oas/functions/oasUnusedComponent.ts
  src/rulesets/oas/index.json
Labels: enhancement
