Repository stoplightio/spectral, pull requests merged in 2022-08, with the labels that each got.

#2026 feat(core): improve ruleset validation
  jest.config.js
  karma.conf.ts
  package.json
  packages/cli/src/services/__tests__/linter.test.ts
  packages/core/package.json
  packages/core/src/ruleset/__tests__/__fixtures__/overrides/formats.ts
  packages/core/src/ruleset/__tests__/ruleset.test.ts
  packages/core/src/ruleset/function.ts
  packages/core/src/ruleset/mergers/rules.ts
  packages/core/src/ruleset/meta/js-extensions.json
  packages/core/src/ruleset/validation/__tests__/validation.test.ts
  packages/core/src/ruleset/validation/ajv.ts
  packages/core/src/ruleset/validation/assertions.ts
  packages/core/src/ruleset/validation/errors.ts
  packages/functions/src/__tests__/__helpers__/tester.ts
  packages/functions/src/__tests__/alphabetical.test.ts
  packages/functions/src/__tests__/casing.test.ts
  packages/functions/src/__tests__/defined.test.ts
  packages/functions/src/__tests__/enumeration.test.ts
  packages/functions/src/__tests__/falsy.test.ts
  packages/functions/src/__tests__/length.test.ts
  packages/functions/src/__tests__/pattern.test.ts
  packages/functions/src/__tests__/schema.test.ts
  packages/functions/src/__tests__/truthy.test.ts
  packages/functions/src/__tests__/unreferencedReusableObject.test.ts
  packages/functions/src/__tests__/xor.test.ts
  test-utils/index.ts
  test-utils/matchers.ts
  tsconfig.json
  yarn.lock
Labels: enhancement, team/dnc

#2174 fix(ruleset-bundler): never externalize builtins
  packages/ruleset-bundler/package.json
  packages/ruleset-bundler/src/__tests__/index.jest.test.ts
  packages/ruleset-bundler/src/plugins/__tests__/builtins.spec.ts
  packages/ruleset-bundler/src/plugins/__tests__/skypack.spec.ts
  packages/ruleset-bundler/src/plugins/builtins.ts
  yarn.lock
Labels: t/bug

#2243 fix(rulesets): __importDefault undefined
  packages/rulesets/src/shared/functions/index.ts
  tsconfig.json
Labels: t/bug

#2234 docs(rulesets): link to spectral-rulesets
  .github/CODEOWNERS
  README.md
Labels: documentation

#2230 docs(repo): update readme installation and usage
  README.md
Labels: documentation

#2213 chore(test-harness): generate tests out of scenarios
  .circleci/config.yml
  .eslintignore
  .gitignore
  .swcrc
  package.json
  packages/ruleset-migrator/package.json
  test-harness/helpers.ts
  test-harness/index.ts
  test-harness/jest.config.js
  test-harness/jest.config.mjs
  test-harness/scenarios/overrides/aliases.scenario
  test-harness/scenarios/overrides/extends.scenario
  test-harness/scenarios/overrides/pointers.scenario
  test-harness/scenarios/overrides/rules.scenario
  test-harness/scripts/generate-tests.ts
  test-harness/spawn.ts
  test-harness/src/consts.ts
  test-harness/src/parser.ts
  test-harness/src/runtime/index.ts
  test-harness/src/runtime/nix.ts
  test-harness/src/runtime/win.ts
  test-harness/src/suite.ts
  test-harness/src/utils.ts
  yarn.lock
Labels: chore

#2224 feat(rulesets): check uniqueness of AsyncAPI messages
  docs/reference/asyncapi-rules.md
  packages/rulesets/src/asyncapi/__tests__/asyncapi-message-messageId-uniqueness.test.ts
  packages/rulesets/src/asyncapi/__tests__/asyncapi-operation-operationId-uniqueness.test.ts
  packages/rulesets/src/asyncapi/functions/asyncApi2MessageIdUniqueness.ts
  packages/rulesets/src/asyncapi/functions/asyncApi2OperationIdUniqueness.ts
  packages/rulesets/src/asyncapi/functions/utils/getAllMessages.ts
  packages/rulesets/src/asyncapi/functions/utils/getAllOperations.ts
  packages/rulesets/src/asyncapi/index.ts
Labels: enhancement, AsyncAPI

#2251 fix(cli): missing line break
  packages/cli/src/commands/lint.ts
Labels: t/bug

#2247 fix(ruleset-migrator): http/https uris not followed correctly
  packages/ruleset-migrator/src/__tests__/ruleset.test.ts
  packages/ruleset-migrator/src/tree/index.ts
Labels: t/bug
