Repository stoplightio/spectral, pull requests merged in 2022-06, with the labels that each got.

#2172 fix(cli): do not show 'or higher' if severity equals error
  packages/cli/src/commands/lint.ts
  test-harness/scenarios/custom-ref-resolver.scenario
  test-harness/scenarios/ignored-unrecognized-format.scenario
  test-harness/scenarios/oas3.1/petstore.scenario
  test-harness/scenarios/operation-security-defined.oas3.scenario
  test-harness/scenarios/parameter-description-links.oas3.scenario
  test-harness/scenarios/severity/display-errors.scenario
  test-harness/scenarios/severity/fail-on-warn-no-warn.scenario
  test-harness/scenarios/valid-no-errors.oas2.scenario
Labels: t/bug

#2126 feat(rulesets): add rule to validate message's examples
  docs/reference/asyncapi-rules.md
  packages/rulesets/src/asyncapi/__tests__/asyncapi-message-examples.test.ts
  packages/rulesets/src/asyncapi/functions/asyncApi2MessageExamplesValidation.ts
  packages/rulesets/src/asyncapi/index.ts
Labels: enhancement, AsyncAPI

#2173 fix(core): bump nimma from 0.2.1 to 0.2.2
  packages/core/package.json
  yarn.lock
Labels: t/bug

#2194 feat(ruleset-bundler): add fullOutput option to bundleRuleset
  packages/ruleset-bundler/src/__tests__/index.test.ts
  packages/ruleset-bundler/src/index.ts
Labels: enhancement
