Repository stoplightio/spectral, pull requests merged in 2022-10, with the labels that each got.

#2304 fix(core): async functions have undefined paths
  packages/core/src/__tests__/linter.test.ts
  packages/core/src/runner/lintNode.ts
Labels: t/bug

#2284 fix(rulesets): handle empty payload and headers in AsyncAPI message's examples validation
  packages/rulesets/src/asyncapi/__tests__/asyncapi-latest-version.test.ts
  packages/rulesets/src/asyncapi/__tests__/asyncapi-message-examples.test.ts
  packages/rulesets/src/asyncapi/functions/asyncApi2DocumentSchema.ts
  packages/rulesets/src/asyncapi/functions/asyncApi2MessageExamplesValidation.ts
  packages/rulesets/src/asyncapi/functions/utils/__tests__/mergeTraits.test.ts
  packages/rulesets/src/asyncapi/functions/utils/mergeTraits.ts
  packages/rulesets/src/asyncapi/functions/utils/specs.ts
  packages/rulesets/src/asyncapi/index.ts
  test-harness/scenarios/asyncapi2-streetlights.scenario
Labels: enhancement, AsyncAPI

#2307 feat(ruleset-migrator): relax validation
  packages/ruleset-migrator/src/__tests__/ruleset.test.ts
  packages/ruleset-migrator/src/transformers/formats.ts
  packages/ruleset-migrator/src/validation/schema.ts
  packages/ruleset-migrator/src/validation/types.ts
Labels: enhancement

#2309 chore(core): tweak StringifiedRuleset and StringifiedRule
  packages/core/src/ruleset/rule.ts
  packages/core/src/ruleset/ruleset.ts
  packages/core/src/ruleset/types.ts
Labels: chore

#2271 fix(ruleset-bundler): virtualFs plugin not recognizing files
  karma.conf.ts
  packages/ruleset-bundler/src/plugins/virtualFs.ts
Labels: t/bug

#2267 fix(core): support utf8 surrogates
  packages/core/package.json
  packages/core/src/__tests__/linter.test.ts
  packages/core/src/runner/runner.ts
  packages/core/src/runner/utils/__tests__/__fixtures__/duplicate-validation-results.json
  packages/core/src/runner/utils/__tests__/__fixtures__/non-duplicate-validation-results.json
  packages/core/src/runner/utils/__tests__/__fixtures__/random-results.ts
  packages/core/src/runner/utils/__tests__/results.test.ts
  packages/core/src/runner/utils/results.ts
  packages/core/src/spectral.ts
  packages/core/src/utils/__tests__/prepareResults.test.ts
  packages/core/src/utils/__tests__/sortResults.test.ts
  packages/core/src/utils/index.ts
  packages/core/src/utils/prepareResults.ts
  yarn.lock
Labels: t/bug

#2318 feat(ruleset-bundler): skypack plugin accepts ignore list
  packages/ruleset-bundler/src/plugins/__tests__/skypack.spec.ts
  packages/ruleset-bundler/src/plugins/skypack.ts
Labels: enhancement

#2272 feat(cli): use Content-Type header to detect ruleset format
  packages/cli/package.json
  packages/cli/src/services/__tests__/linter.test.ts
  packages/cli/src/services/linter/utils/getRuleset.ts
  yarn.lock
Labels: enhancement

#2268 fix(cli): peer dependency incorrectly met
  package.json
  packages/cli/package.json
  packages/cli/src/services/linter/utils/__tests__/listFiles.test.ts
  packages/cli/src/services/linter/utils/getRuleset.ts
  yarn.lock
Labels: t/bug

#2321 docs(repo): add documentation as codeowners for toc.json
  .github/CODEOWNERS
Labels: documentation

#2322 docs(repo): fix custom function examples with targetVal
  docs/guides/5-custom-functions.md
Labels: documentation
