Repository stoplightio/spectral, pull requests merged in 2022-01, with the labels that each got.

#2014 fix(ruleset-migrator): order of functions property should not matter
  packages/ruleset-migrator/package.json
  packages/ruleset-migrator/src/__tests__/__fixtures__/functions-variant-4/output.cjs
  packages/ruleset-migrator/src/__tests__/__fixtures__/functions-variant-4/output.mjs
  packages/ruleset-migrator/src/__tests__/__fixtures__/functions-variant-5/output.cjs
  packages/ruleset-migrator/src/__tests__/__fixtures__/functions-variant-5/output.mjs
  packages/ruleset-migrator/src/__tests__/__fixtures__/functions-variant-5/ruleset.yaml
  packages/ruleset-migrator/src/__tests__/__fixtures__/functions-variant-6/output.cjs
  packages/ruleset-migrator/src/__tests__/__fixtures__/functions-variant-6/output.mjs
  packages/ruleset-migrator/src/__tests__/__fixtures__/functions-variant-6/ruleset.yaml
  packages/ruleset-migrator/src/__tests__/__fixtures__/functions-variant-7/output.cjs
  packages/ruleset-migrator/src/__tests__/__fixtures__/functions-variant-7/output.mjs
  packages/ruleset-migrator/src/__tests__/__fixtures__/functions-variant-7/ruleset.yaml
  packages/ruleset-migrator/src/__tests__/__fixtures__/rules-variant-1/output.cjs
  packages/ruleset-migrator/src/__tests__/__fixtures__/rules-variant-1/output.mjs
  packages/ruleset-migrator/src/__tests__/__fixtures__/rules-variant-1/ruleset.yaml
  packages/ruleset-migrator/src/index.ts
  packages/ruleset-migrator/src/transformers/except.ts
  packages/ruleset-migrator/src/transformers/extends.ts
  packages/ruleset-migrator/src/transformers/formats.ts
  packages/ruleset-migrator/src/transformers/functions.ts
  packages/ruleset-migrator/src/transformers/rules.ts
  packages/ruleset-migrator/src/tree/index.ts
  packages/ruleset-migrator/src/types.ts
  yarn.lock
Labels: t/bug

#2020 fix(rulesets): update dependencies
  packages/rulesets/package.json
  yarn.lock
Labels: dependencies

#2001 chore(repo): enable esModuleInterop
  packages/cli/src/formatters/__tests__/pretty.test.ts
  packages/cli/src/formatters/__tests__/stylish.test.ts
  packages/cli/src/formatters/pretty.ts
  packages/cli/src/formatters/stylish.ts
  packages/cli/src/index.ts
  packages/cli/src/services/__tests__/linter.test.ts
  packages/cli/src/services/linter/utils/getRuleset.ts
  packages/cli/src/services/linter/utils/listFiles.ts
  packages/core/src/__tests__/spectral.jest.test.ts
  packages/core/src/ruleset/rulesetFunction.ts
  packages/core/src/ruleset/utils/minimatch.ts
  packages/core/src/types/spectral.ts
  packages/core/src/utils/__tests__/prepareResults.test.ts
  packages/functions/src/schema/index.ts
  packages/ruleset-bundler/src/utils/isPackageImport.ts
  packages/ruleset-migrator/src/__tests__/ruleset.test.ts
  packages/ruleset-migrator/src/tree/scope.ts
  packages/rulesets/src/asyncapi/functions/asyncApi2PayloadValidation.ts
  packages/rulesets/src/oas/functions/oasSchema.ts
  test-utils/node/index.ts
  tsconfig.json
Labels: chore

#2016 feat(core): support multiple JSONPath expressions for aliases
  docs/guides/4-custom-rulesets.md
  packages/core/src/meta/rule.schema.json
  packages/core/src/meta/ruleset.schema.json
  packages/core/src/meta/shared.json
  packages/core/src/ruleset/__tests__/__helpers__/print.ts
  packages/core/src/ruleset/__tests__/ruleset.test.ts
  packages/core/src/ruleset/__tests__/validation.test.ts
  packages/core/src/ruleset/mergers/rules.ts
  packages/core/src/ruleset/rule.ts
  packages/core/src/ruleset/rule/index.ts
  packages/core/src/ruleset/ruleset.ts
  packages/core/src/ruleset/types.ts
  packages/core/src/ruleset/utils/guards.ts
  packages/core/src/runner/lintNode.ts
  packages/core/src/types/function.ts
Labels: enhancement

#2029 fix(cli): add path to JUnit testcase name
  packages/cli/src/formatters/__tests__/junit.test.ts
  packages/cli/src/formatters/junit.ts
Labels: t/bug

#2028 fix(cli): correctly handle special characters in JUnit failure details
  packages/cli/src/formatters/__tests__/__fixtures__/errors-with-special-xml-strings.json
  packages/cli/src/formatters/__tests__/junit.test.ts
  packages/cli/src/formatters/junit.ts
  test-harness/scenarios/formats/results-format-junit.scenario
Labels: t/bug

#2022 fix(ruleset-migrator): resolve npm packages correctly
  packages/ruleset-migrator/package.json
  packages/ruleset-migrator/src/__tests__/ruleset.jest.test.ts
  packages/ruleset-migrator/src/__tests__/ruleset.test.ts
  packages/ruleset-migrator/src/index.ts
  packages/ruleset-migrator/src/transformers/extends.ts
  packages/ruleset-migrator/src/transformers/functions.ts
  packages/ruleset-migrator/src/tree/index.ts
  packages/ruleset-migrator/src/types.ts
  packages/ruleset-migrator/src/utils/__tests__/isKnownNpmRegistry.spec.ts
  packages/ruleset-migrator/src/utils/__tests__/isPackageImport.spec.ts
  packages/ruleset-migrator/src/utils/isKnownNpmRegistry.ts
  packages/ruleset-migrator/src/utils/isPackageImport.ts
  yarn.lock
Labels: t/bug

#2033 feat(core): aliases take only array-ish given
  docs/guides/4-custom-rulesets.md
  packages/core/src/meta/ruleset.schema.json
  packages/core/src/meta/shared.json
  packages/core/src/ruleset/__tests__/__fixtures__/overrides/aliases/scope.ts
  packages/core/src/ruleset/__tests__/ruleset.test.ts
  packages/core/src/ruleset/__tests__/validation.test.ts
  packages/core/src/ruleset/rule.ts
  packages/core/src/ruleset/types.ts
  packages/rulesets/src/oas/index.ts
  test-harness/scenarios/aliases.scenario
  test-harness/scenarios/overrides/aliases.scenario
Labels: enhancement, breaking

#2039 docs(repo): clarify how to version pin rulesets
  docs/guides/7-sharing-rulesets.md
Labels: documentation

#2041 fix(runtime): update node-fetch from ^2.6.1 to ^2.6.7
  packages/runtime/package.json
  yarn.lock
Labels: dependencies, security
