Repository stoplightio/spectral, pull requests merged in 2022-02, with the labels that each got.

#2050 fix(rulesets): operation-tags should fail on empty array
  CONTRIBUTING.md
  packages/rulesets/src/oas/__tests__/operation-tags.test.ts
  packages/rulesets/src/oas/index.ts
Labels: t/bug

#2044 fix(cli): output to stdout not working with multiple output formatters
  packages/cli/package.json
  packages/cli/src/commands/__tests__/lint.test.ts
  packages/cli/src/commands/lint.ts
  yarn.lock
Labels: t/bug

#1171 chore(repo): make it possible run test-harness on Windows
  .circleci/config.yml
  package.json
  test-harness/helpers.ts
  test-harness/index.ts
  test-harness/scenarios/fail-on-unmatched-glob-patterns.scenario
  test-harness/scenarios/formats/results-default-output.scenario
  test-harness/scenarios/help-no-document.scenario
  test-harness/scenarios/proxy-agent.scenario
  test-harness/scenarios/rules-matching-multiple-places.scenario
  test-harness/scenarios/severity/fail-on-error.scenario
  test-harness/scenarios/stdin-document-with-errors.scenario
  test-harness/scenarios/stdin-filepath.scenario
  test-harness/scenarios/stdin.scenario
  test-harness/scenarios/strict-commands.scenario
  test-harness/scenarios/strict-options.scenario
  test-harness/spawn.ts
  yarn.lock
Labels: chore

#2047 docs(repo): update changelogs
  .circleci/config.yml
  docs/guides/4-custom-rulesets.md
  package.json
  packages/cli/CHANGELOG.md
  packages/core/CHANGELOG.md
  packages/formats/CHANGELOG.md
  packages/functions/CHANGELOG.md
  packages/ruleset-bundler/CHANGELOG.md
  packages/ruleset-migrator/CHANGELOG.md
  packages/rulesets/CHANGELOG.md
  packages/runtime/CHANGELOG.md
  yarn.lock
Labels: chore

#2058 fix(core): bump nimma from 0.1.7 to 0.1.8
  packages/core/package.json
  yarn.lock
Labels: t/bug

#2063 docs(repo): added steps for getting rulesets
  README.md
  docs/guides/2-cli.md
Labels: documentation
